import { Link, useParams } from 'react-router-dom';
import { useLanguage } from '../i18n/LanguageProvider';
import { AppLucideIcon } from '../design-system/icon-registry';
import { FeatureIcon, IconButton, MetricCard, PageHeader, SearchField, StatusBadge } from '../components/preview/PreviewPrimitives';
import '../styles/design-preview.css';

const copy = {
  en: { dashboard:'Dashboard', clients:'Clients', library:'Library', training:'Training', nutrition:'Nutrition', messages:'Messages', settings:'Settings', preview:'Design preview', good:'Good morning, Coach', intro:'Here is what needs your attention across the team today.', add:'Add client', attention:'Players need attention', attentionDetail:'2 more than yesterday', active:'Active clients', activeDetail:'Across your current roster', completion:'Workout completion', completionDetail:'Up 6% this week', unread:'Unread messages', unreadDetail:'3 from VIP clients', today:'Today’s coaching focus', focusHelp:'A clear queue based on messages, adherence, and scheduled check-ins.', view:'View all', checkup:'Check-in due', low:'Low activity', replied:'Message received', open:'Open profile', schedule:'Today’s schedule', checkups:'check-ins remaining', completed:'4 of 7 complete', quick:'Quick actions', program:'Build a program', workout:'Create a workout', invite:'Invite a client', last8:'Last trained 8 days ago', vipTime:'VIP · Local time 10:42', ends:'Program ends tomorrow', exerciseLibrary:'Exercise library', libraryIntro:'Create and manage reusable movements for client programming.', newExercise:'New exercise', search:'Search exercises', searchPlaceholder:'Search by name, category, or muscle group', filters:'Filters', all:'All exercises', custom:'My exercises', platform:'Platform', exercise:'Exercise', category:'Category', muscles:'Muscle groups', tracking:'Tracking', updated:'Updated', actions:'Actions', edit:'Edit exercise', strength:'Strength', mobility:'Mobility', cardio:'Cardio', todayWord:'Today', yesterday:'Yesterday', days:'3 days ago', reps:'Sets · Reps · Weight', time:'Time · Distance', squat:'Goblet squat', press:'Half-kneeling press', hip:'Hip mobility flow', walk:'Incline treadmill walk', quads:'Quadriceps, Glutes', shoulders:'Shoulders, Core', hips:'Hips, Hamstrings', full:'Full body' },
  ar: { dashboard:'لوحة التحكم', clients:'العملاء', library:'المكتبة', training:'التدريب', nutrition:'التغذية', messages:'الرسائل', settings:'الإعدادات', preview:'معاينة التصميم', good:'صباح الخير، كابتن', intro:'إليك ما يحتاج إلى اهتمامك في الفريق اليوم.', add:'إضافة عميل', attention:'لاعبون يحتاجون الاهتمام', attentionDetail:'أكثر باثنين من الأمس', active:'العملاء النشطون', activeDetail:'ضمن قائمتك الحالية', completion:'إكمال التمارين', completionDetail:'ارتفاع ٦٪ هذا الأسبوع', unread:'الرسائل غير المقروءة', unreadDetail:'٣ من عملاء VIP', today:'أولوية التدريب اليوم', focusHelp:'قائمة واضحة مبنية على الرسائل والالتزام والمتابعات المجدولة.', view:'عرض الكل', checkup:'موعد متابعة', low:'نشاط منخفض', replied:'رسالة جديدة', open:'فتح الملف', schedule:'جدول اليوم', checkups:'متابعات متبقية', completed:'اكتملت ٤ من ٧', quick:'إجراءات سريعة', program:'إنشاء برنامج', workout:'إنشاء تمرين', invite:'دعوة عميل', last8:'آخر تدريب منذ ٨ أيام', vipTime:'VIP · التوقيت المحلي ١٠:٤٢', ends:'ينتهي البرنامج غدًا', exerciseLibrary:'مكتبة التمارين', libraryIntro:'أنشئ وأدر الحركات القابلة لإعادة الاستخدام في برامج العملاء.', newExercise:'تمرين جديد', search:'بحث التمارين', searchPlaceholder:'ابحث بالاسم أو الفئة أو العضلة', filters:'الفلاتر', all:'كل التمارين', custom:'تماريني', platform:'المنصة', exercise:'التمرين', category:'الفئة', muscles:'المجموعات العضلية', tracking:'التتبع', updated:'آخر تحديث', actions:'الإجراءات', edit:'تعديل التمرين', strength:'قوة', mobility:'مرونة', cardio:'كارديو', todayWord:'اليوم', yesterday:'أمس', days:'منذ ٣ أيام', reps:'مجموعات · تكرارات · وزن', time:'وقت · مسافة', squat:'سكوات الكأس', press:'ضغط نصف الركوع', hip:'حركة مرونة الورك', walk:'مشي مائل على السير', quads:'الفخذ الأمامي، الأرداف', shoulders:'الكتف، الجذع', hips:'الورك، خلف الفخذ', full:'الجسم كاملًا' },
};

const rows = [
  { name:'Goblet squat', category:'strength', muscles:'Quadriceps, Glutes', tracking:'reps', updated:'todayWord' },
  { name:'Half-kneeling press', category:'strength', muscles:'Shoulders, Core', tracking:'reps', updated:'yesterday' },
  { name:'Hip mobility flow', category:'mobility', muscles:'Hips, Hamstrings', tracking:'time', updated:'days' },
  { name:'Incline treadmill walk', category:'cardio', muscles:'Full body', tracking:'time', updated:'days' },
];

export default function DesignPreview() {
  const { view = 'dashboard' } = useParams();
  const { language } = useLanguage();
  const t = copy[language];
  return <div className="preview-root" data-preview-page>
    <aside className="preview-sidebar"><a className="preview-brand" href="/design-preview/dashboard"><span>P</span><strong>Pulse Coach</strong></a><nav aria-label="Preview navigation">
      <PreviewNav to="dashboard" icon="dashboard" label={t.dashboard} active={view === 'dashboard'} />
      <PreviewNav to="library" icon="clients" label={t.clients} />
      <PreviewNav to="library" icon="library" label={t.library} active={view === 'library'} />
      <PreviewNav to="dashboard" icon="training" label={t.training} />
      <PreviewNav to="dashboard" icon="nutrition" label={t.nutrition} />
      <PreviewNav to="dashboard" icon="messages" label={t.messages} />
    </nav><div className="preview-sidebar-bottom"><PreviewNav to="dashboard" icon="settings" label={t.settings} /></div></aside>
    <div className="preview-stage"><header className="preview-utility"><button className="preview-menu" aria-label="Open navigation"><AppLucideIcon name="library" /></button><span className="preview-chip">{t.preview}</span><div><IconButton label={t.search} icon="search" /><IconButton label="Notifications" icon="notifications" /><button className="preview-profile" aria-label="Open profile">CA</button></div></header><main>{view === 'library' ? <LibraryPreview t={t} /> : <DashboardPreview t={t} />}</main></div>
  </div>;
}

function PreviewNav({ to, icon, label, active = false }: { to: string; icon: Parameters<typeof AppLucideIcon>[0]['name']; label: string; active?: boolean }) {
  return <Link to={`/design-preview/${to}`} aria-current={active ? 'page' : undefined} className={active ? 'active' : ''}><span><AppLucideIcon name={icon} size={22} /></span><em>{label}</em></Link>;
}
function DashboardPreview({ t }: { t: typeof copy.en }) {
  return <div className="preview-page"><PageHeader eyebrow={t.dashboard} title={t.good} description={t.intro} action={<button className="preview-primary"><AppLucideIcon name="add" size={18} />{t.add}</button>} />
    <section className="preview-metric-grid" aria-label="Coaching metrics"><MetricCard icon="clients" feature="clients" value="6" label={t.attention} detail={t.attentionDetail} /><MetricCard icon="progress" feature="analytics" value="24" label={t.active} detail={t.activeDetail} /><MetricCard icon="training" feature="training" value="84%" label={t.completion} detail={t.completionDetail} /><MetricCard icon="messages" feature="messages" value="5" label={t.unread} detail={t.unreadDetail} /></section>
    <div className="preview-dashboard-grid"><section className="preview-card preview-focus"><header><div><span className="preview-eyebrow">{t.today}</span><h2>{t.attention}</h2><p>{t.focusHelp}</p></div><button className="preview-text-button">{t.view}<AppLucideIcon name="next" size={16} /></button></header><div className="preview-focus-list"><FocusRow initials="MA" name="Maya Ali" detail={t.last8} badges={<><StatusBadge tone="yellow">{t.checkup}</StatusBadge><StatusBadge tone="pink">{t.low}</StatusBadge></>} open={t.open} /><FocusRow initials="OK" name="Omar Khaled" detail={t.vipTime} badges={<StatusBadge tone="blue">{t.replied}</StatusBadge>} open={t.open} /><FocusRow initials="LN" name="Lina Nassar" detail={t.ends} badges={<StatusBadge tone="yellow">{t.checkup}</StatusBadge>} open={t.open} /></div></section><aside className="preview-dashboard-side"><section className="preview-card preview-tracker"><FeatureIcon name="calendar" feature="analytics" /><span>{t.schedule}</span><strong>3 {t.checkups}</strong><div><i style={{width:'68%'}} /></div><small>{t.completed}</small></section><section className="preview-card preview-actions"><h2>{t.quick}</h2><Action icon="programs" feature="training" text={t.program} /><Action icon="workouts" feature="resources" text={t.workout} /><Action icon="clients" feature="clients" text={t.invite} /></section></aside></div>
  </div>;
}
function FocusRow({ initials, name, detail, badges, open }: { initials:string; name:string; detail:string; badges:React.ReactNode; open:string }) { return <article><span className="preview-avatar">{initials}</span><div><strong>{name}</strong><small>{detail}</small></div><div className="preview-badges">{badges}</div><button className="preview-row-link">{open}<AppLucideIcon name="next" size={16} /></button></article>; }
function Action({ icon, feature, text }: { icon: Parameters<typeof AppLucideIcon>[0]['name']; feature:Parameters<typeof FeatureIcon>[0]['feature']; text:string }) { return <button><FeatureIcon name={icon} feature={feature} /><span>{text}</span><AppLucideIcon name="next" size={16} /></button>; }
function LibraryPreview({ t }: { t: typeof copy.en }) { const localizedRows = rows.map((row, index) => ({...row,name:[t.squat,t.press,t.hip,t.walk][index],muscles:[t.quads,t.shoulders,t.hips,t.full][index]})); return <div className="preview-page"><PageHeader eyebrow={t.library} title={t.exerciseLibrary} description={t.libraryIntro} action={<button className="preview-primary"><AppLucideIcon name="add" size={18} />{t.newExercise}</button>} /><section className="preview-card preview-library"><div className="preview-toolbar"><SearchField label={t.search} placeholder={t.searchPlaceholder} /><button className="preview-secondary"><AppLucideIcon name="filter" size={18} />{t.filters}<span>2</span></button></div><div className="preview-segments" role="tablist" aria-label="Exercise source"><button role="tab" aria-selected="true">{t.all}<span>128</span></button><button role="tab">{t.custom}<span>14</span></button><button role="tab">{t.platform}<span>114</span></button></div><div className="preview-table-wrap"><table><thead><tr><th>{t.exercise}</th><th>{t.category}</th><th>{t.muscles}</th><th>{t.tracking}</th><th>{t.updated}</th><th><span className="sr-only">{t.actions}</span></th></tr></thead><tbody>{localizedRows.map((row, index) => <tr key={row.name}><td data-label={t.exercise}><div className="preview-exercise-name"><FeatureIcon name="exercises" feature={index === 2 ? 'analytics' : 'training'} /><strong>{row.name}</strong></div></td><td data-label={t.category}><StatusBadge tone={row.category === 'strength' ? 'blue' : row.category === 'mobility' ? 'green' : 'pink'}>{t[row.category as 'strength']}</StatusBadge></td><td data-label={t.muscles}>{row.muscles}</td><td data-label={t.tracking}>{t[row.tracking as 'reps']}</td><td data-label={t.updated}>{t[row.updated as 'todayWord']}</td><td><IconButton label={`${t.edit}: ${row.name}`} icon="edit" /></td></tr>)}</tbody></table></div><footer><span>1–4 of 128</span><div><IconButton label="Previous page" icon="back" disabled /><IconButton label="Next page" icon="next" /></div></footer></section></div>; }
