import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { listCoachFoods } from '../../../api/diet';
import type { DietTemplate } from '../../../api/dietTemplates';
import type { DietFoodItem, DietMeal } from '../../../types/database.types';
import FoodPicker from '../../../components/FoodPicker';
import { buildSlots } from '../diet/buildSlots';
import RecipePicker from '../diet/RecipePicker';

export default function SavedMealDayEditor({ coachId, initial, saving, onClose, onSave }: { coachId: string; initial?: DietTemplate; saving: boolean; onClose: () => void; onSave: (value: { name: string; meals: DietMeal[]; comment: string }) => void }) {
  const [name, setName] = useState(initial?.name ?? '');
  const [mealCount, setMealCount] = useState(initial?.meals.filter((meal) => meal.type === 'meal').length || 3);
  const [snackCount, setSnackCount] = useState(initial?.meals.filter((meal) => meal.type === 'snack').length ?? 1);
  const [meals, setMeals] = useState<DietMeal[]>(initial?.meals ?? buildSlots(3, 1));
  const [selected, setSelected] = useState(0);
  const [comment, setComment] = useState(initial?.comment ?? '');
  const foods = useQuery({ queryKey: ['coachFoods', coachId], queryFn: () => listCoachFoods(coachId) });
  const foodNames = (foods.data ?? []).map((food) => food.name);
  const current = meals[selected];
  const patchItem = (index: number, patch: Partial<DietFoodItem>) => setMeals((value) => value.map((meal, mealIndex) => mealIndex === selected ? { ...meal, items: (meal.items ?? []).map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) } : meal));
  const addFood = () => setMeals((value) => value.map((meal, index) => index === selected ? { ...meal, items: [...(meal.items ?? []), { food: '', grams: '', unit: 'grams', quantity: '' }] } : meal));
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= meals.length) return; setMeals((value) => { const next = [...value]; [next[index], next[target]] = [next[target], next[index]]; return next; }); setSelected(target); };
  return <div className="catalog-dialog-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="catalog-dialog saved-meal-day-editor"><header><div><span className="overview-kicker">Saved Meal Days</span><h2>{initial ? 'Edit meal day' : 'Create meal day'}</h2></div><button className="secondary catalog-close" onClick={onClose}>×</button></header><div className="saved-day-editor-body">
    <div className="saved-day-meta"><label>Name<input autoFocus value={name} maxLength={200} onChange={(event) => setName(event.target.value)} placeholder="Example: High protein day" /></label><label>Meals<input type="number" min="0" max="10" value={mealCount} onChange={(event) => setMealCount(Number(event.target.value))} /></label><label>Snacks<input type="number" min="0" max="10" value={snackCount} onChange={(event) => setSnackCount(Number(event.target.value))} /></label><button type="button" className="secondary" onClick={() => { if (!initial || confirm('Regenerate slots and clear the current meals?')) { setMeals(buildSlots(mealCount, snackCount)); setSelected(0); } }}>Generate slots</button></div>
    <div className="saved-day-workspace"><aside><h3>Day arrangement</h3>{meals.map((meal, index) => <div className={selected === index ? 'selected' : ''} key={`${meal.label}-${index}`}><button onClick={() => setSelected(index)}><strong>{meal.label}</strong><small>{meal.items?.length ?? 0} foods</small></button><span><button disabled={index === 0} onClick={() => move(index, -1)}>↑</button><button disabled={index === meals.length - 1} onClick={() => move(index, 1)}>↓</button></span></div>)}</aside><main>{current ? <><label>Meal name<input value={current.label} onChange={(event) => setMeals((value) => value.map((meal, index) => index === selected ? { ...meal, label: event.target.value } : meal))} /></label><RecipePicker coachId={coachId} onUse={(recipe, items) => setMeals((value) => value.map((meal, index) => index === selected ? { ...meal, items: [...(meal.items ?? []), ...items], recipes: [...(meal.recipes ?? []), recipe] } : meal))} />{(current.items ?? []).map((item, index) => <div className="diet-food-row" key={index}><div className="field"><label>Food</label><FoodPicker value={item.food} options={foodNames} onChange={(food) => patchItem(index, { food })} /></div><div className="field"><label>Measure</label><select value={item.unit ?? 'grams'} onChange={(event) => patchItem(index, event.target.value === 'quantity' ? { unit: 'quantity', grams: '' } : { unit: 'grams', quantity: '' })}><option value="grams">Grams</option><option value="quantity">Quantity</option></select></div><div className="field"><label>Amount</label><input type="number" min="0" value={item.unit === 'quantity' ? item.quantity ?? '' : item.grams} onChange={(event) => patchItem(index, item.unit === 'quantity' ? { quantity: event.target.value } : { grams: event.target.value })} /></div><button className="danger" onClick={() => setMeals((value) => value.map((meal, mealIndex) => mealIndex === selected ? { ...meal, items: (meal.items ?? []).filter((_, itemIndex) => itemIndex !== index) } : meal))}>×</button></div>)}<button className="secondary" onClick={addFood}>+ Add food</button></> : <p className="muted">Generate at least one meal or snack.</p>}</main></div>
    <label>Instructions for this day<textarea rows={3} value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Optional instructions for the player" /></label>
  </div><footer><button className="secondary" onClick={onClose}>Cancel</button><button disabled={!name.trim() || meals.length === 0 || saving} onClick={() => onSave({ name, meals, comment })}>{saving ? 'Saving…' : 'Save Meal Day'}</button></footer></section></div>;
}
