import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ban, RefreshCw, ShieldCheck, Undo2 } from 'lucide-react';
import { blockIp, getTrafficSummary, unblockIp } from '../../api/traffic';

export default function AdminTraffic() {
  const [hours, setHours] = useState(24); const qc = useQueryClient();
  const query = useQuery({ queryKey: ['traffic', hours], queryFn: () => getTrafficSummary(hours), refetchInterval: 30_000 });
  const block = useMutation({ mutationFn: ({ ip, reason, expiresAt }: { ip: string; reason: string; expiresAt: string | null }) => blockIp(ip, reason, expiresAt), onSuccess: () => qc.invalidateQueries({ queryKey: ['traffic'] }) });
  const unblock = useMutation({ mutationFn: unblockIp, onSuccess: () => qc.invalidateQueries({ queryKey: ['traffic'] }) });
  const data = query.data; const activeBlocks = new Set((data?.blocks ?? []).map((item) => item.ip));
  function blockAddress(ip: string) { const reason = prompt(`Why block ${ip}?`, 'Suspicious request activity')?.trim(); if (!reason) return; const duration = prompt('Block for how many hours? Leave blank for permanent.', '24')?.trim() ?? ''; const value = Number(duration); const expiresAt = duration && Number.isFinite(value) && value > 0 ? new Date(Date.now() + value * 3_600_000).toISOString() : null; block.mutate({ ip, reason, expiresAt }); }
  return <div className="traffic-page stack">
    <div className="row traffic-heading"><div><h1>Traffic & IP Activity</h1><p className="muted">Aggregated request counts. Passwords, tokens, chats and request bodies are never stored.</p></div><div className="row"><select aria-label="Traffic period" value={hours} onChange={(event) => setHours(Number(event.target.value))}><option value={1}>Last hour</option><option value={24}>Last 24 hours</option><option value={168}>Last 7 days</option></select><button className="secondary" onClick={() => query.refetch()} disabled={query.isFetching}><RefreshCw size={17}/><span>Refresh</span></button></div></div>
    {query.error && <p className="error">{(query.error as Error).message}</p>}
    <div className="traffic-stats"><div><span>Requests</span><strong>{data?.totals.requests ?? 0}</strong></div><div><span>Unique IPs</span><strong>{data?.totals.unique_ips ?? 0}</strong></div><div><span>Errors</span><strong>{data?.totals.errors ?? 0}</strong></div><div><span>Blocked</span><strong>{data?.totals.blocked ?? 0}</strong></div></div>
    <section className="library-table-card"><div className="traffic-section-title"><ShieldCheck size={19}/><strong>Requests by IP</strong></div><div className="clients-table-scroll"><table className="clients-table library-table"><thead><tr><th>IP</th><th>Country</th><th>Platform</th><th>Requests</th><th>Errors</th><th>Blocked</th><th>Last seen</th><th>Action</th></tr></thead><tbody>{(data?.ips ?? []).map((row) => <tr key={`${row.ip}-${row.platform}`}><td><code>{row.ip}</code></td><td>{row.country || '—'}</td><td>{row.platform}</td><td>{row.requests}</td><td>{row.errors}</td><td>{row.blocked}</td><td>{new Date(row.last_seen).toLocaleString()}</td><td>{activeBlocks.has(row.ip) ? <button className="secondary" onClick={() => unblock.mutate(row.ip)}><Undo2 size={15}/><span>Unblock</span></button> : <button className="danger" onClick={() => blockAddress(row.ip)}><Ban size={15}/><span>Block</span></button>}</td></tr>)}</tbody></table></div>{!query.isLoading && !data?.ips.length && <div className="library-empty"><strong>No traffic recorded yet</strong><span>Counts appear after the website and mobile app begin using the gateway.</span></div>}</section>
    <section className="library-table-card"><div className="traffic-section-title"><Ban size={19}/><strong>Recent errors and blocked requests</strong></div><div className="clients-table-scroll"><table className="clients-table library-table"><thead><tr><th>Time</th><th>IP</th><th>Platform</th><th>Request</th><th>Status</th><th>Type</th></tr></thead><tbody>{(data?.events ?? []).map((event) => <tr key={event.id}><td>{new Date(event.occurred_at).toLocaleString()}</td><td><code>{event.ip}</code></td><td>{event.platform}</td><td>{event.method} /{event.route}</td><td>{event.status}</td><td>{event.event_type}</td></tr>)}</tbody></table></div></section>
  </div>;
}
