import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../../auth/AuthContext';
import { completePlayerAssignment, listPlayerAssignments, type PlayerAssignment } from '../../api/playerAssignments';
import { submitAssignmentPhotos, uploadAssignmentPhoto } from '../../api/progressPhotos';
import LoadingSkeleton from '../../components/LoadingSkeleton';
const labels={task:'Task',form:'Form',metric_group:'Metric check-in',meal_plan:'Meal plan',recipe_book:'Recipe book'}as const;
export default function PlayerAssignments(){const{session}=useAuth();const playerId=session!.user.id;const qc=useQueryClient();const query=useQuery({queryKey:['player-assignments',playerId],queryFn:()=>listPlayerAssignments(playerId)});const complete=useMutation({mutationFn:completePlayerAssignment,onSuccess:()=>qc.invalidateQueries({queryKey:['player-assignments',playerId]})});const visible=(query.data??[]).filter(item=>!['meal_plan','recipe_book'].includes(item.item_type));return <div className="stack"><div><h1>Assignments</h1><p className="muted">Forms, tasks, and check-ins shared by your coach.</p></div>{query.isLoading&&<LoadingSkeleton rows={5}/>}<div className="assignments-grid">{visible.map(item=><AssignmentCard key={item.id} item={item} playerId={playerId} onDone={()=>qc.invalidateQueries({queryKey:['player-assignments',playerId]})} complete={()=>complete.mutate(item.id)} busy={complete.isPending}/>)}</div>{query.isSuccess&&visible.length===0&&<div className="card"><p className="muted">No assignments yet.</p></div>}</div>}
function AssignmentCard({item,playerId,onDone,complete,busy}:{item:PlayerAssignment;playerId:string;onDone:()=>void;complete:()=>void;busy:boolean}){const[files,setFiles]=useState<File[]>([]);const[error,setError]=useState('');const[uploading,setUploading]=useState(false);const photoTask=item.item_type==='task'&&item.snapshot.task_type==='progress_photo';async function submit(){setUploading(true);setError('');try{if(!files.length)throw new Error('Choose at least one photo.');const paths=[];for(const file of files)paths.push(await uploadAssignmentPhoto(playerId,item.id,file));await submitAssignmentPhotos(item.id,paths);onDone()}catch(value){setError((value as Error).message)}finally{setUploading(false)}}return <article className="card stack"><span className="badge active">{labels[item.item_type]}</span><h2>{item.snapshot.title??labels[item.item_type]}</h2>{item.snapshot.summary&&<p>{item.snapshot.summary}</p>}<small className="muted">Scheduled for {new Date(item.scheduled_for).toLocaleDateString()}</small>{photoTask?<><label>Upload photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={event=>setFiles([...(event.target.files??[])])}/></label>{files.length>0&&<small>{files.length} photo{files.length===1?'':'s'} selected</small>}<button disabled={item.status==='complete'||uploading} onClick={submit}>{item.status==='complete'?'Completed ✓':uploading?'Uploading…':'Submit photos'}</button>{item.snapshot.add_uploads_to_progress_photos&&<small className="muted">These photos will also appear in Progress Photos.</small>}</>:<button disabled={item.status==='complete'||busy} onClick={complete}>{item.status==='complete'?'Completed ✓':'Mark complete'}</button>}{error&&<p className="error">{error}</p>}</article>}
