import { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { Screen, textStyles } from '../../components/Screen';
import { Button, Input } from '../../components/Controls';
import { useAuth } from '../../auth/AuthProvider';
import { supabase } from '../../lib/supabase';
import { colors } from '../../theme';
export default function CoachSupportScreen(){const{session}=useAuth();const[messages,setMessages]=useState<any[]>([]);const[body,setBody]=useState('');useEffect(()=>{supabase.from('admin_messages').select('*').eq('coach_id',session!.user.id).order('created_at').limit(100).then(({data})=>setMessages(data??[]));const channel=supabase.channel(`coach-support-${session!.user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'admin_messages',filter:`coach_id=eq.${session!.user.id}`},payload=>setMessages(current=>[...current,payload.new])).subscribe();return()=>{void supabase.removeChannel(channel)};},[session]);async function send(){const text=body.trim();if(!text)return;setBody('');const{error}=await supabase.from('admin_messages').insert({coach_id:session!.user.id,sender_id:session!.user.id,body:text});if(error){setBody(text);Alert.alert('Could not send',error.message);}}return <Screen title="Admin Support">{messages.map(m=><View key={m.id} style={[styles.bubble,m.sender_id===session!.user.id&&styles.mine]}><Text style={textStyles.body}>{m.body||`[${m.attachment_type}]`}</Text></View>)}<Input value={body} onChangeText={setBody} multiline placeholder="Message the admin team"/><Button onPress={send} disabled={!body.trim()}>SEND</Button></Screen>}
const styles=StyleSheet.create({bubble:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:12,padding:12,maxWidth:'85%'},mine:{alignSelf:'flex-end',backgroundColor:colors.accentSoft}});
