import { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import { Card, Screen, textStyles } from '../../components/Screen';
import { useAuth } from '../../auth/AuthProvider';
import { supabase } from '../../lib/supabase';
import { colors, radius } from '../../theme';

export default function CoachDashboardScreen(){const{session,profile}=useAuth();const[data,setData]=useState<any|null>(null);const[refreshing,setRefreshing]=useState(false);async function load(){setRefreshing(true);const today=new Date().toISOString().slice(0,10);const[links,chats,checks]=await Promise.all([supabase.from('coach_player_links').select('id,status,subscription_end_date,is_vip,checkup_weekdays,player_id').eq('coach_id',session!.user.id),supabase.from('chat_messages').select('player_id,created_at').eq('coach_id',session!.user.id).order('created_at',{ascending:false}).limit(100),supabase.from('checkups').select('player_id,is_checked').eq('coach_id',session!.user.id).eq('check_date',today)]);const rows=links.data??[];const weekday=new Date().getDay();const scheduled=rows.filter(x=>x.player_id&&(x.is_vip||(x.checkup_weekdays??[]).includes(weekday)));setData({active:rows.filter(x=>x.status==='active'&&x.subscription_end_date>=today&&x.player_id).length,vip:rows.filter(x=>x.is_vip&&x.player_id).length,pending:rows.filter(x=>!x.player_id).length,scheduled:scheduled.length,checked:(checks.data??[]).filter(x=>x.is_checked).length,conversations:new Set((chats.data??[]).map(x=>x.player_id)).size});setRefreshing(false)}useEffect(()=>{void load()},[session]);return <Screen title={`Welcome, ${profile?.name?.split(' ')[0]||'Coach'}`} subtitle="Your coaching workspace at a glance" refreshing={refreshing} onRefresh={load}>{!data?<ActivityIndicator color={colors.accent}/>:<><View style={styles.grid}><Metric value={data.active} label="Active players"/><Metric value={data.vip} label="VIP players" vip/><Metric value={data.pending} label="Pending keys"/><Metric value={data.conversations} label="Conversations"/></View><Card><Text style={textStyles.eyebrow}>Today</Text><Text style={styles.focus}>{data.checked} / {data.scheduled}</Text><Text style={textStyles.heading}>Player check-ups completed</Text><View style={styles.track}><View style={[styles.fill,{width:`${data.scheduled?Math.min(100,data.checked/data.scheduled*100):0}%`}]}/></View><Text style={textStyles.muted}>{data.scheduled-data.checked>0?`${data.scheduled-data.checked} players still need attention.`:'You are caught up for today.'}</Text></Card><Card><Text style={textStyles.heading}>Quick workflow</Text><Text style={textStyles.muted}>Open Players for profiles and analysis, Plans for programming, Messages for conversations, or Check-ups for today’s priority list.</Text></Card></>}</Screen>}
function Metric({value,label,vip=false}:{value:number;label:string;vip?:boolean}){return <View style={[styles.metric,vip&&styles.vip]}><Text style={[styles.number,vip&&{color:colors.vip}]}>{value}</Text><Text style={textStyles.muted}>{label}</Text></View>}
const styles=StyleSheet.create({grid:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{width:'48%',minHeight:96,justifyContent:'center',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:14},vip:{borderColor:'#694a16'},number:{color:colors.text,fontSize:30,fontWeight:'900'},focus:{color:colors.accent,fontSize:38,fontWeight:'900'},track:{height:8,borderRadius:99,backgroundColor:colors.surfaceSoft,overflow:'hidden'},fill:{height:'100%',backgroundColor:colors.success,borderRadius:99}});
