import { useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Card, Screen, textStyles } from '../../components/Screen';
import { Button, Input } from '../../components/Controls';
import { useAuth } from '../../auth/AuthProvider';
import { supabase } from '../../lib/supabase';
import { dayNames } from '../../lib/dates';
import { colors } from '../../theme';

type Mode = 'schedule' | 'workout' | 'diet' | 'assign';
export default function CoachPlanScreen() {
  const { session } = useAuth(); const coachId = session!.user.id;
  const [players,setPlayers]=useState<any[]>([]),[playerId,setPlayerId]=useState('');
  const [week,setWeek]=useState(1),[day,setDay]=useState(1),[mode,setMode]=useState<Mode>('schedule');
  const [schedule,setSchedule]=useState<any[]>([]),[workouts,setWorkouts]=useState<any[]>([]),[diets,setDiets]=useState<any[]>([]),[programs,setPrograms]=useState<any[]>([]);
  async function base(){const[p,w,d,g]=await Promise.all([supabase.from('coach_player_links').select('player_id,profiles!coach_player_links_player_id_fkey(name,email)').eq('coach_id',coachId).eq('status','active').not('player_id','is',null),supabase.from('workout_templates').select('id,name').order('name'),supabase.from('diet_templates').select('id,name').order('name'),supabase.from('program_templates').select('*').order('name')]);const list=(p.data??[]).map((x:any)=>({id:x.player_id,name:x.profiles?.name||x.profiles?.email}));setPlayers(list);if(!playerId&&list[0])setPlayerId(list[0].id);setWorkouts(w.data??[]);setDiets(d.data??[]);setPrograms(g.data??[])}
  async function load(){if(!playerId)return;const{data,error}=await supabase.from('program_days').select('*,workouts(*,exercises(*))').eq('player_id',playerId).eq('week_number',week);if(error)Alert.alert('Could not load',error.message);else setSchedule(data??[])}
  useEffect(()=>{void base()},[session]);useEffect(()=>{void load()},[playerId,week]);
  const selected=schedule.find(x=>x.day_of_week===day);
  async function ensure(d=day,type='training'){const{data,error}=await supabase.from('program_days').upsert({player_id:playerId,coach_id:coachId,week_number:week,day_of_week:d,day_type:type,updated_at:new Date().toISOString()},{onConflict:'player_id,week_number,day_of_week'}).select().single();if(error)throw error;return data}
  async function remove(){if(!selected)return;const{error}=await supabase.from('program_days').delete().eq('id',selected.id);if(error)Alert.alert('Could not delete',error.message);else void load()}
  async function duplicate(){if(!selected)return;const target=(day+1)%7;try{const d=await ensure(target,selected.day_type);for(const w of selected.workouts??[]){const{data:nw,error}=await supabase.from('workouts').insert({program_day_id:d.id,name:w.name,position:w.position,template_id:w.template_id}).select().single();if(error)throw error;if(w.exercises?.length){const{error:e}=await supabase.from('exercises').insert(w.exercises.map((x:any)=>({workout_id:nw.id,position:x.position,name:x.name,template_exercise_id:x.template_exercise_id,is_template_override:x.is_template_override,target_sets:x.target_sets,target_reps:x.target_reps,target_weight:x.target_weight,coach_comment:x.coach_comment,coach_video_url:x.coach_video_url,coach_video_is_external:x.coach_video_is_external})));if(e)throw e}}setDay(target);void load()}catch(e){Alert.alert('Could not duplicate',(e as Error).message)}}
  return <Screen title="Build Plans" subtitle="Weekly training, diet, and saved programs"><Card><Text style={textStyles.heading}>Player</Text><View style={styles.wrap}>{players.map(p=><Chip key={p.id} active={playerId===p.id} text={p.name} onPress={()=>setPlayerId(p.id)}/>)}</View><View style={styles.row}><Button secondary onPress={()=>setWeek(Math.max(1,week-1))}>←</Button><Text style={styles.week}>WEEK {week}</Text><Button secondary onPress={()=>setWeek(week+1)}>→</Button></View><View style={styles.days}>{[6,0,1,2,3,4,5].map(x=><Chip key={x} active={day===x} text={dayNames[x].slice(0,3)} onPress={()=>setDay(x)}/>)}</View></Card><View style={styles.wrap}>{(['schedule','workout','diet','assign'] as Mode[]).map(x=><Chip key={x} active={mode===x} text={x} onPress={()=>setMode(x)}/>)}</View>{mode==='schedule'?<Schedule value={selected} create={ensure} remove={remove} duplicate={duplicate}/>:mode==='workout'?<Workout playerId={playerId} coachId={coachId} week={week} day={day} templates={workouts} reload={load}/>:mode==='diet'?<Diet playerId={playerId} coachId={coachId} week={week} day={day} templates={diets}/>:<Assign playerId={playerId} programs={programs}/>}</Screen>
}
function Chip({active,text,onPress}:{active:boolean;text:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,active&&styles.active]}><Text style={styles.chipText}>{text.toUpperCase()}</Text></Pressable>}
function Schedule({value,create,remove,duplicate}:{value:any;create:(d?:number,t?:string)=>Promise<any>;remove:()=>void;duplicate:()=>void}){if(!value)return <Card><Text style={textStyles.muted}>No plan for this day.</Text><Button onPress={()=>create()}>CREATE TRAINING DAY</Button><Button secondary onPress={()=>create(undefined,'rest')}>CREATE REST DAY</Button></Card>;return <Card><Text style={textStyles.heading}>{value.day_type==='rest'?'Rest day':'Training day'}</Text>{(value.workouts??[]).map((w:any)=><View key={w.id} style={styles.block}><Text style={textStyles.heading}>{w.name||'Saved workout'}</Text>{(w.exercises??[]).map((e:any)=><Text key={e.id} style={textStyles.muted}>• {e.name||'Saved exercise'} · {e.target_sets??'—'}×{e.target_reps??'—'}</Text>)}</View>)}<Button secondary onPress={duplicate}>DUPLICATE DAY</Button><Button danger onPress={remove}>DELETE DAY</Button></Card>}
function Workout({playerId,coachId,week,day,templates,reload}:{playerId:string;coachId:string;week:number;day:number;templates:any[];reload:()=>void}){const[name,setName]=useState(''),[exercise,setExercise]=useState(''),[sets,setSets]=useState('3'),[reps,setReps]=useState('10'),[weight,setWeight]=useState(''),[note,setNote]=useState('');async function ensure(){const{data,error}=await supabase.from('program_days').upsert({player_id:playerId,coach_id:coachId,week_number:week,day_of_week:day,day_type:'training'},{onConflict:'player_id,week_number,day_of_week'}).select().single();if(error)throw error;return data}async function add(){if(!name.trim()||!exercise.trim())return;try{const d=await ensure();const{data:w,error}=await supabase.from('workouts').insert({program_day_id:d.id,name:name.trim(),position:0}).select().single();if(error)throw error;const{error:e}=await supabase.from('exercises').insert({workout_id:w.id,name:exercise.trim(),position:0,target_sets:Number(sets)||null,target_reps:reps||null,target_weight:weight||null,coach_comment:note||null,coach_video_url:null,coach_video_is_external:false});if(e)throw e;setExercise('');void reload()}catch(e){Alert.alert('Could not add',(e as Error).message)}}async function saved(id:string){try{const d=await ensure();const{error}=await supabase.rpc('assign_workout_template',{p_program_day_id:d.id,p_template_id:id,p_position:0});if(error)throw error;void reload()}catch(e){Alert.alert('Could not assign',(e as Error).message)}}return <><Card><Text style={textStyles.heading}>New workout</Text><Input value={name} onChangeText={setName} placeholder="Workout name"/><Input value={exercise} onChangeText={setExercise} placeholder="Exercise name"/><View style={styles.row}><Input style={styles.flex} value={sets} onChangeText={setSets} placeholder="Sets"/><Input style={styles.flex} value={reps} onChangeText={setReps} placeholder="Reps"/><Input style={styles.flex} value={weight} onChangeText={setWeight} placeholder="Weight"/></View><Input value={note} onChangeText={setNote} multiline placeholder="Coach note"/><Button onPress={add}>ADD WORKOUT</Button></Card>{templates.map(t=><Button key={t.id} secondary onPress={()=>saved(t.id)}>ADD SAVED: {t.name}</Button>)}</>}
function Diet({playerId,coachId,week,day,templates}:{playerId:string;coachId:string;week:number;day:number;templates:any[]}){const[label,setLabel]=useState('Meal 1'),[food,setFood]=useState(''),[grams,setGrams]=useState(''),[comment,setComment]=useState('');async function save(){if(!food.trim())return;const meals=[{type:'meal',label,content:'',items:[{food:food.trim(),grams}]}];const{error}=await supabase.from('diet_days').upsert({player_id:playerId,coach_id:coachId,week_number:week,day_of_week:day,meals,comment:comment||null,is_template_override:true},{onConflict:'player_id,week_number,day_of_week'});if(error)Alert.alert('Could not save',error.message)}async function saved(id:string){const{error}=await supabase.rpc('assign_diet_template',{p_player_id:playerId,p_week:week,p_day_of_week:day,p_template_id:id});if(error)Alert.alert('Could not assign',error.message)}return <><Card><Text style={textStyles.heading}>Diet day</Text><Input value={label} onChangeText={setLabel} placeholder="Meal label"/><Input value={food} onChangeText={setFood} placeholder="Food"/><Input value={grams} onChangeText={setGrams} placeholder="Grams"/><Input value={comment} onChangeText={setComment} multiline placeholder="Coach comment"/><Button onPress={save}>SAVE DIET DAY</Button></Card>{templates.map(t=><Button key={t.id} secondary onPress={()=>saved(t.id)}>ASSIGN SAVED: {t.name}</Button>)}</>}
function Assign({playerId,programs}:{playerId:string;programs:any[]}){const[start,setStart]=useState('1');async function apply(p:any){const{error}=await(supabase.rpc as any)('assign_program_template_to_player',{p_player_id:playerId,p_program_template_id:p.id,p_start_week:Number(start)||1});if(error)Alert.alert('Could not assign',error.message);else Alert.alert('Assigned',`${p.name} starts in week ${start}.`)}return <><Card><Text style={textStyles.heading}>Assign whole program</Text><Input value={start} onChangeText={setStart} keyboardType="number-pad" placeholder="Starting week"/><Text style={textStyles.muted}>This replaces the schedule across the saved program’s weeks.</Text></Card>{programs.map(p=><Card key={p.id}><Text style={textStyles.heading}>{p.name}</Text><Text style={textStyles.muted}>{p.difficulty} · {p.duration_weeks} weeks</Text><Button onPress={()=>apply(p)}>ASSIGN PROGRAM</Button></Card>)}</>}
const styles=StyleSheet.create({wrap:{flexDirection:'row',flexWrap:'wrap',gap:6},chip:{padding:9,borderWidth:1,borderColor:colors.border,borderRadius:99},active:{backgroundColor:colors.accent},chipText:{color:colors.text,fontSize:10,fontWeight:'900'},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},days:{flexDirection:'row',flexWrap:'wrap',gap:4},week:{color:colors.text,fontWeight:'900'},block:{borderTopWidth:1,borderTopColor:colors.border,paddingTop:8,gap:3},flex:{flex:1}});
