import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../../auth/AuthContext';
import { createLibraryExercise, deleteLibraryExercise, listLibraryExercises, updateLibraryExercise, type LibraryExercise } from '../../api/exerciseLibrary';
import LoadingSkeleton from '../../components/LoadingSkeleton';

const split = (value: string) => value.split(',').map((part) => part.trim()).filter(Boolean);
export default function ExerciseLibrary() {
  const { session } = useAuth(); const coachId = session!.user.id; const qc = useQueryClient();
  const [search, setSearch] = useState(''); const [editing, setEditing] = useState<LibraryExercise | 'new' | null>(null);
  const [name, setName] = useState(''); const [category, setCategory] = useState(''); const [muscles, setMuscles] = useState(''); const [patterns, setPatterns] = useState('');
  const query = useQuery({ queryKey: ['exercise-library', coachId], queryFn: () => listLibraryExercises(coachId) });
  const save = useMutation({ mutationFn: () => { if (!name.trim() || !category.trim()) throw new Error('Exercise and category are required.'); const input = { name: name.trim(), category: category.trim(), target_muscle_groups: split(muscles), movement_patterns: split(patterns) }; return editing === 'new' ? createLibraryExercise(coachId, input) : updateLibraryExercise(editing!.id, input); }, onSuccess: async () => { await qc.invalidateQueries({ queryKey: ['exercise-library', coachId] }); close(); } });
  const remove = useMutation({ mutationFn: deleteLibraryExercise, onSuccess: () => qc.invalidateQueries({ queryKey: ['exercise-library', coachId] }) });
  const rows = (query.data ?? []).filter((item) => `${item.name} ${item.category} ${item.target_muscle_groups.join(' ')} ${item.movement_patterns.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
  function open(item?: LibraryExercise) { setEditing(item ?? 'new'); setName(item?.name ?? ''); setCategory(item?.category ?? ''); setMuscles(item?.target_muscle_groups.join(', ') ?? ''); setPatterns(item?.movement_patterns.join(', ') ?? ''); }
  function close() { setEditing(null); setName(''); setCategory(''); setMuscles(''); setPatterns(''); save.reset(); }
  return <div className="exercise-library-page"><div className="library-heading"><div><h1>Exercise Library</h1><p>Create exercises once and reuse them in any player program.</p></div><button onClick={() => open()}>+ Add New Exercise</button></div>
    {query.isLoading && <LoadingSkeleton rows={5} />}{query.error && <p className="error">{(query.error as Error).message}</p>}
    {query.data && <div className="library-table-card"><div className="clients-search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by exercise name…" /></div><div className="clients-table-scroll"><table className="clients-table library-table"><thead><tr><th>Exercise</th><th>Category</th><th>Target Muscle Groups</th><th>Movement Patterns</th><th>Created On</th><th></th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.category}</td><td>{item.target_muscle_groups.join(', ') || '—'}</td><td>{item.movement_patterns.join(', ') || '—'}</td><td>{new Date(item.created_at).toLocaleDateString()}</td><td className="library-actions"><button className="secondary" onClick={() => open(item)}>Edit</button><button className="danger" disabled={remove.isPending} onClick={() => window.confirm(`Delete ${item.name}?`) && remove.mutate(item.id)}>Delete</button></td></tr>)}</tbody></table></div>{rows.length === 0 && <div className="library-empty"><strong>No Exercises Found</strong><span>Start adding exercises to reuse in programs.</span></div>}</div>}
    {editing && <div className="workout-modal-backdrop"><section className="workout-modal exercise-library-modal" role="dialog" aria-modal="true"><header><h2>{editing === 'new' ? 'Add Exercise' : 'Edit Exercise'}</h2><button className="modal-close" onClick={close}>×</button></header><div className="workout-modal-body"><div className="field"><label>Exercise</label><input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Barbell Squat" maxLength={200} /></div><div className="field"><label>Category</label><input value={category} onChange={(event) => setCategory(event.target.value)} placeholder="Strength" maxLength={100} /></div><div className="field"><label>Target Muscle Groups</label><input value={muscles} onChange={(event) => setMuscles(event.target.value)} placeholder="Quadriceps, Glutes, Hamstrings" /><small>Separate multiple items with commas.</small></div><div className="field"><label>Movement Patterns</label><input value={patterns} onChange={(event) => setPatterns(event.target.value)} placeholder="Squat, Knee dominant" /><small>Separate multiple items with commas.</small></div>{save.error && <p className="error">{(save.error as Error).message}</p>}</div><footer><button className="secondary" onClick={close}>Cancel</button><button disabled={save.isPending} onClick={() => save.mutate()}>{save.isPending ? 'Saving…' : 'Save Exercise'}</button></footer></section></div>}
  </div>;
}
