import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../../auth/AuthContext';
import { addLibraryRelation, archiveCoachLibraryItem, listCoachLibraryItems, listLibraryRelations, publishCoachLibraryItem, removeLibraryRelation, saveCoachLibraryItem, type CoachLibraryItem, type LibraryRelationRow } from '../../api/coachLibrary';
import { getRecipeSnapshot, listPublishedRecipes, type RecipeOption } from '../../api/nutritionLibrary';
import LoadingSkeleton from '../../components/LoadingSkeleton';

const DAYS=['Saturday','Sunday','Monday','Tuesday','Wednesday','Thursday','Friday'];

export default function MealPlanLibrary(){
 const{session}=useAuth();const coachId=session!.user.id;const qc=useQueryClient();const[planId,setPlanId]=useState('');const[week,setWeek]=useState(1);const[createOpen,setCreateOpen]=useState(false);const[addRecipe,setAddRecipe]=useState<RecipeOption|null>(null);const[recipeSearch,setRecipeSearch]=useState('');const[detailId,setDetailId]=useState('');
 const plans=useQuery({queryKey:['coach-library','meal-plans',coachId],queryFn:()=>listCoachLibraryItems('meal-plans',coachId)});const selected=plans.data?.find(x=>x.id===planId)??plans.data?.[0];
 const entries=useQuery({queryKey:['meal-plan-entries',selected?.id],queryFn:()=>listLibraryRelations('meal-plans',selected!.id,coachId),enabled:!!selected});
 const recipes=useQuery({queryKey:['published-recipes',coachId],queryFn:()=>listPublishedRecipes(coachId)});const detail=useQuery({queryKey:['recipe-detail',detailId],queryFn:()=>getRecipeSnapshot(detailId),enabled:!!detailId});
 const refreshPlans=()=>qc.invalidateQueries({queryKey:['coach-library','meal-plans',coachId]});const publish=useMutation({mutationFn:(id:string)=>publishCoachLibraryItem('meal-plans',id),onSuccess:refreshPlans});const archive=useMutation({mutationFn:(id:string)=>archiveCoachLibraryItem('meal-plans',id),onSuccess:async()=>{setPlanId('');await refreshPlans()}});const remove=useMutation({mutationFn:(row:LibraryRelationRow)=>removeLibraryRelation('meal-plans',row),onSuccess:()=>entries.refetch()});
 const visibleRecipes=useMemo(()=>(recipes.data??[]).filter(x=>`${x.title} ${x.summary??''}`.toLowerCase().includes(recipeSearch.toLowerCase())),[recipes.data,recipeSearch]);const weekCount=Number(selected?.meta.week_count??1);const rows=(entries.data?.rows??[]).filter(row=>Number(row.raw.week_number)===week);
 return <div className="meal-planner-page"><header className="catalog-heading"><div><span className="overview-kicker">Nutrition Library</span><h1>Meal Plans</h1><p>Build reusable weekly nutrition schedules, then apply them from a player’s Diet page.</p></div><button onClick={()=>setCreateOpen(true)}>+ Create meal plan</button></header>
 <div className="meal-planner-layout"><aside className="meal-plan-sidebar"><h3>Your plans</h3>{plans.isLoading?<LoadingSkeleton rows={4}/>:<div className="meal-plan-list">{(plans.data??[]).map(plan=><button className={selected?.id===plan.id?'active':''} onClick={()=>{setPlanId(plan.id);setWeek(1)}} key={plan.id}><span><strong>{plan.title}</strong><small>{plan.meta.week_count as number} week{Number(plan.meta.week_count)===1?'':'s'}</small></span><span className={`catalog-status ${plan.lifecycle}`}>{plan.lifecycle}</span></button>)}</div>}</aside>
 <main className="meal-plan-workspace">{selected?<><div className="meal-plan-toolbar"><div><h2>{selected.title}</h2><p>{selected.summary||'Reusable player meal schedule'}</p></div><div><select value={week} onChange={e=>setWeek(Number(e.target.value))}>{Array.from({length:weekCount},(_,i)=>i+1).map(x=><option value={x} key={x}>Week {x}</option>)}</select>{selected.lifecycle!=='published'&&<button className="secondary" onClick={()=>publish.mutate(selected.id)}>Publish</button>}<button className="danger" onClick={()=>confirm(`Archive ${selected.title}?`)&&archive.mutate(selected.id)}>Archive</button></div></div><div className="meal-calendar">{DAYS.map((day,index)=><section key={day}><header><strong>{day}</strong><small>{rows.filter(row=>Number(row.raw.day_number)===index+1).length} meals</small></header><div>{rows.filter(row=>Number(row.raw.day_number)===index+1).map(row=><article key={row.id}><span><strong>{row.raw.meal_name}</strong><small>{row.title} · {row.raw.meal_type??'meal'}</small></span><button aria-label={`Remove ${row.raw.meal_name}`} onClick={()=>remove.mutate(row)}>×</button></article>)}<button className="meal-calendar-add" onClick={()=>setAddRecipe({id:'',title:'Custom meal',summary:null,servings:1,instructions:null,bookIds:[]})}>+ Add meal</button></div></section>)}</div></>:<div className="catalog-empty"><h2>No meal plans yet</h2><p>Create a plan to start arranging recipes by week and day.</p><button onClick={()=>setCreateOpen(true)}>Create meal plan</button></div>}</main>
 <aside className="meal-recipe-library"><h3>Recipe library</h3><input value={recipeSearch} onChange={e=>setRecipeSearch(e.target.value)} placeholder="Search recipes"/>{visibleRecipes.map(recipe=><article key={recipe.id}><button className="recipe-card-main" onClick={()=>setDetailId(recipe.id)}><span className="recipe-card-art">{recipe.title.slice(0,2).toUpperCase()}</span><span><strong>{recipe.title}</strong><small>{recipe.servings} servings</small></span></button><button onClick={()=>setAddRecipe(recipe)}>Add</button></article>)}{recipes.isSuccess&&visibleRecipes.length===0&&<p className="muted">Publish recipes to use them here.</p>}</aside></div>
 {createOpen&&<CreateMealPlan coachId={coachId} onClose={()=>setCreateOpen(false)} onCreated={async id=>{await refreshPlans();setPlanId(id);setCreateOpen(false)}}/>}{addRecipe&&selected&&<AddMealDialog plan={selected} initialRecipe={addRecipe} recipes={recipes.data??[]} week={week} onClose={()=>setAddRecipe(null)} onAdded={async()=>{await entries.refetch();setAddRecipe(null)}}/>}{detailId&&<div className="catalog-dialog-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDetailId('')}><section className="catalog-dialog recipe-detail-dialog"><header><h2>{detail.data?.recipe.title??'Recipe'}</h2><button className="secondary catalog-close" onClick={()=>setDetailId('')}>×</button></header><div>{detail.isLoading?<LoadingSkeleton rows={5}/>:detail.data&&<><p>{detail.data.recipe.servings} servings</p><h3>Ingredients</h3><ul>{detail.data.recipe.ingredients.map((x,i)=><li key={i}><span>{x.food}</span><strong>{x.quantity} {x.unit}</strong></li>)}</ul><h3>Instructions</h3><p>{detail.data.recipe.instructions||'No instructions added.'}</p></>}</div></section></div>}</div>
}

function CreateMealPlan({coachId,onClose,onCreated}:{coachId:string;onClose:()=>void;onCreated:(id:string)=>void}){const[name,setName]=useState('');const[weeks,setWeeks]=useState(1);const save=useMutation({mutationFn:()=>saveCoachLibraryItem('meal-plans',coachId,null,{title:name,summary:'',lifecycle:'draft',shareMode:'private',numberValue:weeks}),onSuccess:onCreated});return <div className="catalog-dialog-backdrop"><section className="catalog-dialog"><header><h2>Create meal plan</h2><button className="secondary catalog-close" onClick={onClose}>×</button></header><form onSubmit={e=>{e.preventDefault();save.mutate()}}><div className="field"><label>Name</label><input autoFocus value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>Number of weeks</label><input type="number" min="1" max="52" value={weeks} onChange={e=>setWeeks(Number(e.target.value))}/></div><footer><button type="button" className="secondary" onClick={onClose}>Cancel</button><button disabled={!name.trim()||save.isPending}>Create</button></footer></form></section></div>}

function AddMealDialog({plan,initialRecipe,recipes,week,onClose,onAdded}:{plan:CoachLibraryItem;initialRecipe:RecipeOption;recipes:RecipeOption[];week:number;onClose:()=>void;onAdded:()=>void}){const[day,setDay]=useState(1);const[type,setType]=useState<'meal'|'snack'>('meal');const[search,setSearch]=useState('');const[selected,setSelected]=useState<string[]>(initialRecipe.id?[initialRecipe.id]:[]);const[customName,setCustomName]=useState('');const visible=recipes.filter(x=>x.title.toLowerCase().includes(search.toLowerCase()));const add=useMutation({mutationFn:async()=>{if(selected.length){for(const id of selected){const recipe=recipes.find(x=>x.id===id)!;await addLibraryRelation('meal-plans',plan.id,{choiceId:id,label:recipe.title,amount:week,secondaryAmount:day,mealType:type})}}else await addLibraryRelation('meal-plans',plan.id,{label:customName,amount:week,secondaryAmount:day,mealType:type})},onSuccess:onAdded});return <div className="catalog-dialog-backdrop"><section className="catalog-dialog add-meals-dialog"><header><div><h2>Add meals</h2><small>Select one or more saved recipes.</small></div><button className="secondary catalog-close" onClick={onClose}>×</button></header><form onSubmit={e=>{e.preventDefault();add.mutate()}}><div className="catalog-form-row"><div className="field"><label>Day</label><select value={day} onChange={e=>setDay(Number(e.target.value))}>{DAYS.map((x,i)=><option value={i+1} key={x}>{x}</option>)}</select></div><div className="field"><label>Type</label><select value={type} onChange={e=>setType(e.target.value as 'meal'|'snack')}><option value="meal">Meal</option><option value="snack">Snack</option></select></div></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search saved recipes"/><div className="add-meal-gallery">{visible.map(recipe=><label className={selected.includes(recipe.id)?'selected':''} key={recipe.id}><input type="checkbox" checked={selected.includes(recipe.id)} onChange={()=>setSelected(current=>current.includes(recipe.id)?current.filter(id=>id!==recipe.id):[...current,recipe.id])}/><span className="recipe-card-art">{recipe.title.slice(0,2).toUpperCase()}</span><span><strong>{recipe.title}</strong><small>{recipe.servings} servings</small></span></label>)}</div><div className="field"><label>Or add a custom meal</label><input value={customName} disabled={selected.length>0} onChange={e=>setCustomName(e.target.value)} placeholder="Custom meal name"/></div>{add.error&&<p className="error">{(add.error as Error).message}</p>}<footer><button type="button" className="secondary" onClick={onClose}>Cancel</button><button disabled={(!selected.length&&!customName.trim())||add.isPending}>Add {selected.length||1} to Week {week}</button></footer></form></section></div>}
