import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../../auth/AuthContext';
import { archiveCoachLibraryItem, listCoachLibraryItems, listLibraryRelations, publishCoachLibraryItem, removeLibraryRelation, type CoachLibraryItem, type LibraryRelationRow } from '../../api/coachLibrary';
import { createMealPlan, reorderMealEntries, saveMealEntry, updateMealPlan } from '../../api/mealPlans';
import { getRecipeSnapshot, listPublishedRecipes, type RecipeOption } from '../../api/nutritionLibrary';
import LoadingSkeleton from '../../components/LoadingSkeleton';

const DAYS=['Saturday','Sunday','Monday','Tuesday','Wednesday','Thursday','Friday'];
const DEFAULT_MEALS=['Breakfast','Lunch','Dinner','Snack'];

export default function MealPlanLibrary(){
 const{session}=useAuth();const coachId=session!.user.id;const qc=useQueryClient();const[planId,setPlanId]=useState('');const[week,setWeek]=useState(1);const[day,setDay]=useState(1);const[view,setView]=useState<'week'|'day'>('week');const[createOpen,setCreateOpen]=useState(false);const[editing,setEditing]=useState<LibraryRelationRow|null>(null);const[addDay,setAddDay]=useState<number|null>(null);const[recipeSearch,setRecipeSearch]=useState('');const[detailId,setDetailId]=useState('');const[dragged,setDragged]=useState<LibraryRelationRow|null>(null);
 const plans=useQuery({queryKey:['coach-library','meal-plans',coachId],queryFn:()=>listCoachLibraryItems('meal-plans',coachId)});const selected=plans.data?.find(x=>x.id===planId)??plans.data?.[0];
 const entries=useQuery({queryKey:['meal-plan-entries',selected?.id],queryFn:()=>listLibraryRelations('meal-plans',selected!.id,coachId),enabled:!!selected});const recipes=useQuery({queryKey:['published-recipes',coachId],queryFn:()=>listPublishedRecipes(coachId)});const detail=useQuery({queryKey:['recipe-detail',detailId],queryFn:()=>getRecipeSnapshot(detailId),enabled:!!detailId});
 const refreshPlans=()=>qc.invalidateQueries({queryKey:['coach-library','meal-plans',coachId]});const publish=useMutation({mutationFn:(id:string)=>publishCoachLibraryItem('meal-plans',id),onSuccess:refreshPlans});const archive=useMutation({mutationFn:(id:string)=>archiveCoachLibraryItem('meal-plans',id),onSuccess:async()=>{setPlanId('');await refreshPlans()}});const remove=useMutation({mutationFn:(row:LibraryRelationRow)=>removeLibraryRelation('meal-plans',row),onSuccess:()=>entries.refetch()});
 const dietary=useMutation({mutationFn:(value:boolean)=>updateMealPlan(selected!.id,{showDietaryInfo:value}),onSuccess:refreshPlans});const reorder=useMutation({mutationFn:(rows:{id:string;position:number}[])=>reorderMealEntries(rows),onSuccess:()=>entries.refetch()});
 const visibleRecipes=useMemo(()=>(recipes.data??[]).filter(x=>`${x.title} ${x.summary??''}`.toLowerCase().includes(recipeSearch.toLowerCase())),[recipes.data,recipeSearch]);const weekCount=Number(selected?.meta.week_count??1);const weekRows=(entries.data?.rows??[]).filter(row=>Number(row.raw.week_number)===week).sort((a,b)=>Number(a.raw.position)-Number(b.raw.position));
 const moveEntry=(target:LibraryRelationRow)=>{if(!dragged||dragged.id===target.id)return;const sameDay=weekRows.filter(row=>Number(row.raw.day_number)===Number(target.raw.day_number));const from=sameDay.findIndex(row=>row.id===dragged.id);const to=sameDay.findIndex(row=>row.id===target.id);if(from<0||to<0)return;const ordered=[...sameDay];ordered.splice(to,0,ordered.splice(from,1)[0]);reorder.mutate(ordered.map((row,index)=>({id:row.id,position:index})))};
 return <div className="meal-planner-page"><header className="catalog-heading"><div><span className="overview-kicker">Nutrition Library</span><h1>Meal Plan Templates</h1><p>Build multi-week meal programs from published recipes, then assign them from a player’s Diet page.</p></div><button onClick={()=>setCreateOpen(true)}>+ Create meal plan</button></header>
 <div className="meal-planner-layout"><aside className="meal-plan-sidebar"><h3>Your plans</h3>{plans.isLoading?<LoadingSkeleton rows={4}/>:<div className="meal-plan-list">{(plans.data??[]).map(plan=><button className={selected?.id===plan.id?'active':''} onClick={()=>{setPlanId(plan.id);setWeek(1);setDay(1)}} key={plan.id}><span><strong>{plan.title}</strong><small>{plan.meta.week_count as number} week{Number(plan.meta.week_count)===1?'':'s'}</small></span><span className={`catalog-status ${plan.lifecycle}`}>{plan.lifecycle}</span></button>)}</div>}</aside>
 <main className="meal-plan-workspace">{selected?<><div className="meal-plan-toolbar"><div>{Boolean(selected.meta.cover_url)&&<img className="meal-plan-cover" src={String(selected.meta.cover_url)} alt=""/>}<span><h2>{selected.title}</h2><p>{selected.summary||'Reusable player meal schedule'}</p></span></div><div><div className="meal-view-toggle"><button className={view==='week'?'active secondary':'secondary'} onClick={()=>setView('week')}>Week</button><button className={view==='day'?'active secondary':'secondary'} onClick={()=>setView('day')}>Day</button></div><select value={week} onChange={e=>setWeek(Number(e.target.value))}>{Array.from({length:weekCount},(_,i)=>i+1).map(x=><option value={x} key={x}>Week {x}</option>)}</select>{selected.lifecycle!=='published'&&<button onClick={()=>publish.mutate(selected.id)}>Publish</button>}<button className="danger" onClick={()=>confirm(`Archive ${selected.title}?`)&&archive.mutate(selected.id)}>Archive</button></div></div><label className="meal-dietary-toggle"><input type="checkbox" checked={Boolean(selected.meta.show_dietary_info)} onChange={e=>dietary.mutate(e.target.checked)}/> Show dietary information on recipe cards</label>
 {view==='day'&&<div className="meal-day-tabs">{DAYS.map((name,index)=><button className={day===index+1?'active':''} onClick={()=>setDay(index+1)} key={name}>{name}</button>)}</div>}
 <div className={`meal-calendar ${view==='day'?'day-view':''}`}>{DAYS.map((dayName,index)=>{const dayNumber=index+1;if(view==='day'&&day!==dayNumber)return null;const rows=weekRows.filter(row=>Number(row.raw.day_number)===dayNumber);return <section key={dayName}><header><strong>{dayName}</strong><small>{rows.length} recipes</small></header><div>{rows.map(row=><article draggable onDragStart={()=>setDragged(row)} onDragOver={e=>e.preventDefault()} onDrop={()=>moveEntry(row)} key={row.id}><button className="meal-card-main" onClick={()=>row.raw.dish_id&&setDetailId(row.raw.dish_id)}><strong>{row.raw.meal_name}</strong><span>{row.title}</span>{Boolean(selected.meta.show_dietary_info)&&<small>{recipeDietary(recipes.data??[],row.raw.dish_id)}</small>}</button><div><button className="secondary" onClick={()=>setEditing(row)}>Replace</button><button aria-label={`Remove ${row.raw.meal_name}`} onClick={()=>remove.mutate(row)}>×</button></div></article>)}<button className="meal-calendar-add" onClick={()=>setAddDay(dayNumber)}>+ Add meal</button>{view==='day'&&DEFAULT_MEALS.filter(name=>!rows.some(row=>row.raw.meal_name===name)).map(name=><button className="meal-empty-slot" onClick={()=>{setAddDay(dayNumber);setEditing({id:'',title:'',detail:'',raw:{meal_name:name,meal_type:name==='Snack'?'snack':'meal'}})}} key={name}>+ {name}</button>)}</div></section>})}</div></>:<div className="catalog-empty"><h2>No meal plans yet</h2><p>Create a plan to start arranging recipes by week and day.</p><button onClick={()=>setCreateOpen(true)}>Create meal plan</button></div>}</main>
 <aside className="meal-recipe-library"><h3>Recipe library</h3><input value={recipeSearch} onChange={e=>setRecipeSearch(e.target.value)} placeholder="Search recipes"/>{visibleRecipes.map(recipe=><article key={recipe.id}><button className="recipe-card-main" onClick={()=>setDetailId(recipe.id)}><span className="recipe-card-art">{recipe.title.slice(0,2).toUpperCase()}</span><span><strong>{recipe.title}</strong><small>{recipe.servings} servings</small></span></button><button onClick={()=>{setAddDay(day);setEditing({id:'',title:recipe.title,detail:'',raw:{dish_id:recipe.id,meal_name:'Lunch',meal_type:'meal'}})}}>Add</button></article>)}{recipes.isSuccess&&visibleRecipes.length===0&&<p className="muted">Publish recipes to use them here.</p>}</aside></div>
 {createOpen&&<CreateMealPlan coachId={coachId} onClose={()=>setCreateOpen(false)} onCreated={async id=>{await refreshPlans();setPlanId(id);setCreateOpen(false)}}/>}{(addDay!==null||editing)&&selected&&<MealEntryDialog plan={selected} initial={editing} recipes={recipes.data??[]} week={week} day={addDay??Number(editing?.raw.day_number??1)} onClose={()=>{setAddDay(null);setEditing(null)}} onSaved={async()=>{await entries.refetch();setAddDay(null);setEditing(null)}}/>}{detailId&&<RecipeDetail detail={detail} onClose={()=>setDetailId('')}/>}</div>
}

function recipeDietary(recipes:RecipeOption[],id:string){const recipe=recipes.find(item=>item.id===id) as RecipeOption&{dietary_labels?:string[]};return recipe?.dietary_labels?.join(' · ')||`${recipe?.servings??1} serving${recipe?.servings===1?'':'s'}`}

function CreateMealPlan({coachId,onClose,onCreated}:{coachId:string;onClose:()=>void;onCreated:(id:string)=>void}){const[name,setName]=useState('');const[description,setDescription]=useState('');const[weeks,setWeeks]=useState(1);const[coverUrl,setCoverUrl]=useState('');const save=useMutation({mutationFn:()=>createMealPlan(coachId,{title:name,description,weekCount:weeks,coverUrl,showDietaryInfo:false}),onSuccess:onCreated});return <div className="catalog-dialog-backdrop"><section className="catalog-dialog"><header><h2>Create meal plan</h2><button className="secondary catalog-close" onClick={onClose}>×</button></header><form onSubmit={e=>{e.preventDefault();save.mutate()}}><div className="field"><label>Name</label><input autoFocus value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>Description</label><textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></div><div className="catalog-form-row"><div className="field"><label>Number of weeks</label><input type="number" min="1" max="52" value={weeks} onChange={e=>setWeeks(Number(e.target.value))}/></div><div className="field"><label>Cover image URL</label><input type="url" value={coverUrl} onChange={e=>setCoverUrl(e.target.value)} placeholder="https://…"/></div></div>{save.error&&<p className="error">{(save.error as Error).message}</p>}<footer><button type="button" className="secondary" onClick={onClose}>Cancel</button><button disabled={!name.trim()||save.isPending}>Create plan</button></footer></form></section></div>}

function MealEntryDialog({plan,initial,recipes,week,day,onClose,onSaved}:{plan:CoachLibraryItem;initial:LibraryRelationRow|null;recipes:RecipeOption[];week:number;day:number;onClose:()=>void;onSaved:()=>void}){const[selectedDay,setSelectedDay]=useState(day);const[recipeId,setRecipeId]=useState(String(initial?.raw.dish_id??''));const[mealName,setMealName]=useState(String(initial?.raw.meal_name??'Breakfast'));const[type,setType]=useState<'meal'|'snack'>(initial?.raw.meal_type==='snack'?'snack':'meal');const save=useMutation({mutationFn:()=>saveMealEntry({id:initial?.id||undefined,planId:plan.id,recipeId,mealName,mealType:type,week,day:selectedDay,position:Number(initial?.raw.position??Date.now()%2_000_000_000)}),onSuccess:onSaved});return <div className="catalog-dialog-backdrop"><section className="catalog-dialog add-meals-dialog"><header><div><h2>{initial?.id?'Replace or edit meal':'Add meal'}</h2><small>Week {week} · {DAYS[selectedDay-1]}</small></div><button className="secondary catalog-close" onClick={onClose}>×</button></header><form onSubmit={e=>{e.preventDefault();save.mutate()}}><div className="field"><label htmlFor="meal-day-select">Day</label><select id="meal-day-select" value={selectedDay} onChange={e=>setSelectedDay(Number(e.target.value))}>{DAYS.map((name,index)=><option value={index+1} key={name}>{name}</option>)}</select></div><div className="catalog-form-row"><div className="field"><label>Meal category</label><input list="meal-categories" value={mealName} onChange={e=>setMealName(e.target.value)}/><datalist id="meal-categories">{DEFAULT_MEALS.map(name=><option key={name}>{name}</option>)}</datalist></div><div className="field"><label>Type</label><select value={type} onChange={e=>setType(e.target.value as 'meal'|'snack')}><option value="meal">Meal</option><option value="snack">Snack</option></select></div></div><div className="field"><label htmlFor="meal-recipe-select">Recipe</label><select id="meal-recipe-select" value={recipeId} onChange={e=>setRecipeId(e.target.value)}><option value="">Choose a saved recipe</option>{recipes.map(recipe=><option value={recipe.id} key={recipe.id}>{recipe.title} · {recipe.servings} serving{recipe.servings===1?'':'s'}</option>)}</select></div>{save.error&&<p className="error">{(save.error as Error).message}</p>}<footer><button type="button" className="secondary" onClick={onClose}>Cancel</button><button disabled={!recipeId||!mealName.trim()||save.isPending}>{initial?.id?'Save changes':'Add meal'}</button></footer></form></section></div>}

function RecipeDetail({detail,onClose}:{detail:ReturnType<typeof useQuery<any>>;onClose:()=>void}){return <div className="catalog-dialog-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="catalog-dialog recipe-detail-dialog"><header><h2>{detail.data?.recipe.title??'Recipe'}</h2><button className="secondary catalog-close" onClick={onClose}>×</button></header><div>{detail.isLoading?<LoadingSkeleton rows={5}/>:detail.data&&<><p>{detail.data.recipe.servings} servings</p><h3>Ingredients</h3><ul>{detail.data.recipe.ingredients.map((x:any,i:number)=><li key={i}><span>{x.food}</span><strong>{x.quantity} {x.unit}</strong></li>)}</ul><h3>Instructions</h3><p>{detail.data.recipe.instructions||'No instructions added.'}</p></>}</div></section></div>}
