import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../../auth/AuthContext';
import { deleteProgramTemplate,duplicateProgramTemplate,getProgramSchedule,listProgramTemplates,saveProgramTemplate,type DraftSchedule,type ProgramTemplate } from '../../api/programTemplates';
import { listWorkoutTemplates } from '../../api/workoutTemplates';

export default function ProgramLibrary(){
  const{session}=useAuth();const coachId=session!.user.id;const qc=useQueryClient();
  const[search,setSearch]=useState('');const[open,setOpen]=useState(false);const[editing,setEditing]=useState<ProgramTemplate|null>(null);
  const[name,setName]=useState('');const[description,setDescription]=useState('');const[difficulty,setDifficulty]=useState('Beginner');const[duration,setDuration]=useState(1);const[week,setWeek]=useState(1);const[schedule,setSchedule]=useState<DraftSchedule>({});const[addDay,setAddDay]=useState<number|null>(null);const[customName,setCustomName]=useState('');
  const query=useQuery({queryKey:['program-templates',coachId],queryFn:()=>listProgramTemplates(coachId)});const workoutQuery=useQuery({queryKey:['workout-templates',coachId],queryFn:()=>listWorkoutTemplates(coachId)});
  const refresh=()=>qc.invalidateQueries({queryKey:['program-templates',coachId]});
  const save=useMutation({mutationFn:()=>saveProgramTemplate(coachId,editing?.id??null,{name:name.trim(),description:description.trim()||null,difficulty,duration_weeks:duration},schedule),onSuccess:async()=>{await refresh();close()}});
  const duplicate=useMutation({mutationFn:duplicateProgramTemplate,onSuccess:refresh});const remove=useMutation({mutationFn:deleteProgramTemplate,onSuccess:refresh});
  const rows=(query.data??[]).filter(x=>x.name.toLowerCase().includes(search.toLowerCase()));
  async function show(item?:ProgramTemplate){setEditing(item??null);setName(item?.name??'');setDescription(item?.description??'');setDifficulty(item?.difficulty??'Beginner');setDuration(item?.duration_weeks??1);setWeek(1);setSchedule(item?await getProgramSchedule(item.id):{});setOpen(true)}
  function close(){setOpen(false);setEditing(null);setName('');setDescription('');setSchedule({});setAddDay(null)}
  function addWorkout(day:number,name:string,templateId:string|null){const key=`${week}-${day}`;setSchedule(current=>({...current,[key]:[...(current[key]??[]),{name,workout_template_id:templateId}]}));setAddDay(null);setCustomName('')}
  function removeWorkout(day:number,index:number){const key=`${week}-${day}`;setSchedule(current=>({...current,[key]:(current[key]??[]).filter((_,i)=>i!==index)}))}
  return <div className="exercise-library-page"><div className="library-heading"><h1>Program Library</h1><button onClick={()=>void show()}>+ Create Program</button></div><div className="library-table-card"><div className="clients-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by program name…"/></div><div className="clients-table-scroll"><table className="clients-table library-table"><thead><tr><th>Name</th><th>Difficulty</th><th>Duration</th><th>Created</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.difficulty}</td><td>{x.duration_weeks} week{x.duration_weeks===1?'':'s'}</td><td>{new Date(x.created_at).toLocaleDateString()}</td><td className="library-actions"><button className="secondary" onClick={()=>void show(x)}>Edit</button><button className="secondary" onClick={()=>duplicate.mutate(x)}>Copy</button><button className="danger" onClick={()=>confirm(`Delete ${x.name}?`)&&remove.mutate(x.id)}>Delete</button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="library-empty"><strong>No Programs Found</strong><span>Create your first reusable program.</span></div>}</div>
  {open&&<div className="workout-modal-backdrop"><section className="workout-modal program-schedule-modal"><header><div><h2>{editing?'Edit Program':'Create Program'}</h2><small>{difficulty} · {duration} week{duration===1?'':'s'}</small></div><button className="modal-close" onClick={close}>×</button></header><div className="workout-modal-body"><div className="program-details-grid"><div className="field"><label>Program Name</label><input autoFocus value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>Difficulty Level</label><select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></div><div className="field program-description"><label>Description (Optional)</label><textarea rows={2} value={description} onChange={e=>setDescription(e.target.value)}/></div><div className="field"><label>Duration (Weeks)</label><input type="number" min="1" max="104" value={duration} onChange={e=>{const n=Math.max(1,Number(e.target.value));setDuration(n);if(week>n)setWeek(n)}}/></div></div><div className="program-week-tabs">{Array.from({length:duration},(_,i)=>i+1).map(x=><button key={x} className={week===x?'active':''} onClick={()=>setWeek(x)}>Week {x}</button>)}</div><div className="program-days-grid">{Array.from({length:7},(_,i)=>i+1).map(day=>{const items=schedule[`${week}-${day}`]??[];return <div className="program-day-column" key={day}><header><strong>Day {day}</strong><button onClick={()=>setAddDay(addDay===day?null:day)}>+</button></header>{addDay===day&&<div className="program-add-menu"><input value={customName} onChange={e=>setCustomName(e.target.value)} placeholder="Workout name"/><button disabled={!customName.trim()} onClick={()=>addWorkout(day,customName.trim(),null)}>Add workout</button><select defaultValue="" onChange={e=>{const x=workoutQuery.data?.find(w=>w.id===e.target.value);if(x)addWorkout(day,x.name,x.id)}}><option value="">Import from Library</option>{(workoutQuery.data??[]).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div>}{items.map((item,index)=><div className="program-workout-chip" key={`${item.name}-${index}`}><span>{item.name}</span><button onClick={()=>removeWorkout(day,index)}>×</button></div>)}</div>})}</div>{save.error&&<p className="error">{(save.error as Error).message}</p>}</div><footer><button className="secondary" onClick={close}>Cancel</button><button disabled={!name.trim()||save.isPending} onClick={()=>save.mutate()}>{save.isPending?'Saving…':editing?'Save Changes':'Create Program'}</button></footer></section></div>}</div>
}
