import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../../auth/AuthContext';
import { deleteWorkoutTemplate,duplicateWorkoutTemplate,getWorkoutTemplate,listWorkoutSections,listWorkoutTemplates,publishWorkoutTemplate,saveWorkoutBlueprint,type WorkoutBlueprintItem,type WorkoutTemplate } from '../../api/workoutTemplates';
import { listLibraryExercises,type LibraryExercise } from '../../api/exerciseLibrary';
import AppIcon from '../../components/AppIcon';
import LoadingSkeleton from '../../components/LoadingSkeleton';

const blankItem=(exercise:LibraryExercise):WorkoutBlueprintItem=>({clientId:crypto.randomUUID(),kind:'exercise',sourceId:exercise.id,name:exercise.name,sets:3,reps:'8-12',seconds:'',restSeconds:60,loadValue:'',loadPercent:'',tempo:'',bilateral:false,note:exercise.default_note??'',chainKey:''});

export default function WorkoutLibrary(){
 const{session}=useAuth();const coachId=session!.user.id;const qc=useQueryClient();const[search,setSearch]=useState('');const[editor,setEditor]=useState<WorkoutTemplate|'new'|null>(null);
 const workouts=useQuery({queryKey:['workout-templates',coachId],queryFn:()=>listWorkoutTemplates(coachId)});
 const remove=useMutation({mutationFn:deleteWorkoutTemplate,onSuccess:()=>qc.invalidateQueries({queryKey:['workout-templates',coachId]})});
 const duplicate=useMutation({mutationFn:duplicateWorkoutTemplate,onSuccess:()=>qc.invalidateQueries({queryKey:['workout-templates',coachId]})});
 const publish=useMutation({mutationFn:publishWorkoutTemplate,onSuccess:()=>qc.invalidateQueries({queryKey:['workout-templates',coachId]})});
 const rows=(workouts.data??[]).filter(x=>`${x.name} ${x.description??''}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="exercise-library-page"><div className="library-heading"><div><span className="overview-kicker">Training catalog</span><h1>Workout Library</h1><p>Build versioned sessions from reusable exercises and sections.</p></div><button onClick={()=>setEditor('new')}><AppIcon name="workout" size={17}/> Add workout</button></div>
 <div className="library-table-card"><div className="clients-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search workouts…" aria-label="Search workouts"/></div>{workouts.isLoading?<LoadingSkeleton rows={5}/>:<div className="clients-table-scroll"><table className="clients-table library-table"><thead><tr><th>Workout</th><th>Status</th><th>Difficulty</th><th>Revision</th><th>Updated</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small>{x.description||'No description'}</small></td><td><span className={`catalog-status ${x.lifecycle??'draft'}`}>{x.lifecycle??'draft'}</span></td><td>{x.difficulty||'—'}</td><td>v{x.revision??1}</td><td>{new Date(x.created_at).toLocaleDateString()}</td><td className="library-actions"><button className="secondary" onClick={()=>setEditor(x)}>Edit</button><button className="secondary" onClick={()=>duplicate.mutate(x.id)}>Copy</button>{x.lifecycle!=='published'&&<button className="secondary" onClick={()=>publish.mutate(x.id)}>Publish</button>}<button className="danger" onClick={()=>confirm(`Archive ${x.name}? Assigned plans remain available.`)&&remove.mutate(x.id)}>Archive</button></td></tr>)}</tbody></table></div>}{!workouts.isLoading&&!rows.length&&<div className="library-empty"><strong>No Workouts Found</strong><span>Create a session blueprint from exercises and reusable sections.</span></div>}</div>
 {editor&&<TrainingBuilder coachId={coachId} template={editor==='new'?null:editor} onClose={()=>setEditor(null)} onSaved={async()=>{await qc.invalidateQueries({queryKey:['workout-templates',coachId]});setEditor(null)}}/>}</div>;
}

function TrainingBuilder({coachId,template,onClose,onSaved}:{coachId:string;template:WorkoutTemplate|null;onClose:()=>void;onSaved:()=>Promise<void>}){
 const[name,setName]=useState(template?.name??'');const[description,setDescription]=useState(template?.description??'');const[difficulty,setDifficulty]=useState(template?.difficulty??'');const[notes,setNotes]=useState(template?.notes??'');const[items,setItems]=useState<WorkoutBlueprintItem[]>([]);const[sourceTab,setSourceTab]=useState<'exercises'|'sections'>('exercises');const[sourceSearch,setSourceSearch]=useState('');const[selected,setSelected]=useState<string|null>(null);const[loaded,setLoaded]=useState(!template);
 const exercises=useQuery({queryKey:['exercise-library',coachId],queryFn:()=>listLibraryExercises(coachId)});const sections=useQuery({queryKey:['workout-sections',coachId],queryFn:()=>listWorkoutSections(coachId)});
 useQuery({queryKey:['workout-blueprint',template?.id],queryFn:async()=>{const data=await getWorkoutTemplate(template!.id);const merged:WorkoutBlueprintItem[]=[...data.exercises.map(x=>({clientId:crypto.randomUUID(),kind:'exercise' as const,sourceId:x.exercise_library_id??x.id,name:x.name,sets:x.target_sets??3,reps:x.target_reps??'',seconds:x.target_seconds?String(x.target_seconds):'',restSeconds:x.rest_seconds??60,loadValue:x.load_value==null?'':String(x.load_value),loadPercent:x.load_percent==null?'':String(x.load_percent),tempo:x.tempo??'',bilateral:x.bilateral,note:x.coach_comment??'',chainKey:x.chain_key??'',position:x.position})),...data.sections.map((x:any)=>({clientId:crypto.randomUUID(),kind:'section' as const,sourceId:x.section_id,name:x.workout_sections?.name??'Section',sets:0,reps:'',seconds:'',restSeconds:0,loadValue:'',loadPercent:'',tempo:'',bilateral:false,note:x.workout_sections?.description??'',chainKey:'',position:x.position}))].sort((a:any,b:any)=>a.position-b.position).map(({position:_,...x}:any)=>x);setItems(merged);setLoaded(true);return data},enabled:!!template&&!loaded});
 const save=useMutation({mutationFn:()=>saveWorkoutBlueprint(template?.id??null,{name,description,difficulty,notes,items}),onSuccess:onSaved});
 const filteredExercises=(exercises.data??[]).filter(x=>`${x.name} ${x.category} ${x.equipment??''}`.toLowerCase().includes(sourceSearch.toLowerCase()));const filteredSections=(sections.data??[]).filter((x:any)=>`${x.name} ${x.format}`.toLowerCase().includes(sourceSearch.toLowerCase()));
 const active=items.find(x=>x.clientId===selected)??null;const exerciseCount=items.filter(x=>x.kind==='exercise').length;const sectionCount=items.length-exerciseCount;const errors=validate(name,items);
 function addExercise(x:LibraryExercise){const item=blankItem(x);setItems(v=>[...v,item]);setSelected(item.clientId)}function addSection(x:any){const item:WorkoutBlueprintItem={clientId:crypto.randomUUID(),kind:'section',sourceId:x.id,name:x.name,sets:0,reps:'',seconds:'',restSeconds:0,loadValue:'',loadPercent:'',tempo:'',bilateral:false,note:x.description??'',chainKey:''};setItems(v=>[...v,item]);setSelected(item.clientId)}
 function patch(id:string,next:Partial<WorkoutBlueprintItem>){setItems(v=>v.map(x=>x.clientId===id?{...x,...next}:x))}function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=items.length)return;setItems(v=>{const copy=[...v];[copy[index],copy[target]]=[copy[target],copy[index]];return copy})}function removeItem(id:string){setItems(v=>v.filter(x=>x.clientId!==id));if(selected===id)setSelected(null)}function chain(index:number){if(index===0)return;const key=items[index].chainKey||items[index-1].chainKey||crypto.randomUUID().slice(0,8);patch(items[index-1].clientId,{chainKey:key});patch(items[index].clientId,{chainKey:key})}
 return <div className="training-builder-backdrop"><section className="training-builder" role="dialog" aria-modal="true" aria-labelledby="training-builder-title"><header><div><span className="overview-kicker">Session blueprint</span><h2 id="training-builder-title">{template?'Edit workout':'Create workout'}</h2></div><div className="training-builder-actions"><button className="secondary" onClick={onClose}>Cancel</button><button disabled={errors.length>0||save.isPending} onClick={()=>save.mutate()}>{save.isPending?'Saving…':'Save & close'}</button></div></header>
 <div className="training-builder-meta"><label>Name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Upper body strength"/></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">Not set</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>Description<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Session goal and context"/></label></div>
 <div className="training-builder-grid"><aside className="training-sources"><div role="tablist" aria-label="Workout sources"><button role="tab" aria-selected={sourceTab==='exercises'} className={sourceTab==='exercises'?'active':''} onClick={()=>setSourceTab('exercises')}>Exercises</button><button role="tab" aria-selected={sourceTab==='sections'} className={sourceTab==='sections'?'active':''} onClick={()=>setSourceTab('sections')}>Sections</button></div><input type="search" value={sourceSearch} onChange={e=>setSourceSearch(e.target.value)} placeholder={`Search ${sourceTab}`} aria-label={`Search ${sourceTab}`}/><div className="training-source-list">{sourceTab==='exercises'?filteredExercises.map(x=><button key={x.id} onClick={()=>addExercise(x)}><span><strong>{x.name}</strong><small>{x.category} · {x.equipment||'No equipment'}</small></span><span aria-hidden="true">＋</span></button>):filteredSections.map((x:any)=><button key={x.id} onClick={()=>addSection(x)}><span><strong>{x.name}</strong><small>{x.format} · {x.rounds??'open'} rounds</small></span><span aria-hidden="true">＋</span></button>)}</div></aside>
 <main className="training-canvas" aria-label="Workout arrangement"><div className="training-canvas-heading"><div><h3>Arrangement</h3><span>{items.length} blocks</span></div><p>Use the arrow buttons for keyboard-accessible ordering.</p></div>{!loaded?<LoadingSkeleton rows={4}/>:items.length===0?<div className="training-canvas-empty"><AppIcon name="workout" size={35}/><strong>Start building your workout</strong><span>Add an exercise or reusable section from the source panel.</span></div>:<ol>{items.map((item,index)=><li key={item.clientId} className={`${selected===item.clientId?'selected':''} ${item.chainKey?'chained':''}`}><button className="training-item-main" onClick={()=>setSelected(item.clientId)}><span className="training-item-index">{index+1}</span><span><strong>{item.name}</strong><small>{item.kind==='section'?'Reusable section':`${item.sets} sets · ${item.reps||`${item.seconds}s`} · ${item.restSeconds}s rest`}</small></span>{item.chainKey&&<em>Group</em>}</button><div className="training-item-actions"><button className="secondary" aria-label={`Move ${item.name} up`} disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button className="secondary" aria-label={`Move ${item.name} down`} disabled={index===items.length-1} onClick={()=>move(index,1)}>↓</button>{item.kind==='exercise'&&<button className="secondary" aria-label={`Link ${item.name} with previous exercise`} disabled={index===0||items[index-1].kind!=='exercise'} onClick={()=>chain(index)}>⌁</button>}<button className="danger" aria-label={`Remove ${item.name}`} onClick={()=>removeItem(item.clientId)}>×</button></div></li>)}</ol>}</main>
 <aside className="training-inspector"><h3>Prescription</h3>{active?<>{active.kind==='section'?<div className="training-section-summary"><span className="catalog-status published">Reusable</span><h4>{active.name}</h4><p>{active.note||'This section keeps its format and ordered prescriptions.'}</p><button className="secondary" onClick={()=>window.open('/coach/section-library','_blank')}>Open section library</button></div>:<ExerciseInspector item={active} onChange={next=>patch(active.clientId,next)}/>}</>:<div className="training-inspector-empty"><span>Select an exercise to edit its prescription.</span></div>}<label className="training-notes">Workout notes<textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Instructions shown with this workout"/></label><div className="training-summary"><span><strong>{exerciseCount}</strong> exercises</span><span><strong>{sectionCount}</strong> sections</span><span><strong>{new Set(items.filter(x=>x.chainKey).map(x=>x.chainKey)).size}</strong> groups</span></div></aside></div>
 <footer><div aria-live="polite">{errors.length?<span className="error">{errors.join(' ')}</span>:<span className="trend-up">Workout is ready to save.</span>}{save.error&&<span className="error">{(save.error as Error).message}</span>}</div><div><button className="secondary" onClick={onClose}>Cancel</button><button disabled={errors.length>0||save.isPending} onClick={()=>save.mutate()}>Save & close</button></div></footer></section></div>;
}

function ExerciseInspector({item,onChange}:{item:WorkoutBlueprintItem;onChange:(next:Partial<WorkoutBlueprintItem>)=>void}){return <div className="prescription-form"><h4>{item.name}</h4><div className="prescription-grid"><label>Sets<input type="number" min="1" max="100" value={item.sets} onChange={e=>onChange({sets:Number(e.target.value)})}/></label><label>Reps<input value={item.reps} onChange={e=>onChange({reps:e.target.value,seconds:''})} placeholder="8-12"/></label><label>Seconds<input type="number" min="1" value={item.seconds} onChange={e=>onChange({seconds:e.target.value,reps:''})}/></label><label>Rest (sec)<input type="number" min="0" value={item.restSeconds} onChange={e=>onChange({restSeconds:Number(e.target.value)})}/></label><label>Load<input type="number" min="0" step="0.5" value={item.loadValue} onChange={e=>onChange({loadValue:e.target.value,loadPercent:''})}/></label><label>% max<input type="number" min="0" max="1000" value={item.loadPercent} onChange={e=>onChange({loadPercent:e.target.value,loadValue:''})}/></label><label>Tempo<input value={item.tempo} onChange={e=>onChange({tempo:e.target.value})} placeholder="3-1-1-0"/></label><label className="prescription-check"><input type="checkbox" checked={item.bilateral} onChange={e=>onChange({bilateral:e.target.checked})}/> Each side</label></div><label>Coaching note<textarea rows={4} value={item.note} onChange={e=>onChange({note:e.target.value})}/></label>{item.chainKey&&<button className="secondary" onClick={()=>onChange({chainKey:''})}>Remove from group</button>}</div>}
function validate(name:string,items:WorkoutBlueprintItem[]){const errors:string[]=[];if(!name.trim())errors.push('Enter a workout name.');if(items.length===0)errors.push('Add at least one exercise or section.');if(items.some(x=>x.kind==='exercise'&&(x.sets<1||(!x.reps&&!x.seconds))))errors.push('Each exercise needs sets and reps or time.');return errors}
