import { supabase } from '../lib/supabase';
export interface ProgramTemplate{id:string;coach_id:string;name:string;description:string|null;difficulty:string;duration_weeks:number;created_at:string;updated_at:string}
export type DraftWorkout={name:string;workout_template_id:string|null;notes:string;exercise_library_ids:string[]};
export type DraftSchedule=Record<string,DraftWorkout[]>;
const table=()=>supabase.from('program_templates' as never) as any;
const daysTable=()=>supabase.from('program_template_days' as never) as any;
const workoutsTable=()=>supabase.from('program_template_day_workouts' as never) as any;
export async function listProgramTemplates(coachId:string):Promise<ProgramTemplate[]>{const{data,error}=await table().select('*').eq('coach_id',coachId).order('created_at',{ascending:false});if(error)throw error;return data??[]}
export async function getProgramSchedule(id:string):Promise<DraftSchedule>{const{data:days,error}=await daysTable().select('*').eq('program_template_id',id);if(error)throw error;if(!days?.length)return{};const{data:workouts,error:wError}=await workoutsTable().select('*').in('program_template_day_id',days.map((d:any)=>d.id)).order('position');if(wError)throw wError;const result:DraftSchedule={};for(const day of days){result[`${day.week_number}-${day.day_number}`]=(workouts??[]).filter((w:any)=>w.program_template_day_id===day.id).map((w:any)=>({name:w.name,workout_template_id:w.workout_template_id,notes:w.notes??'',exercise_library_ids:w.exercise_library_ids??[]}))}return result}
async function saveSchedule(programId:string,schedule:DraftSchedule){const{data:old}=await daysTable().select('id').eq('program_template_id',programId);if(old?.length)await daysTable().delete().eq('program_template_id',programId);for(const[key,items]of Object.entries(schedule)){if(!items.length)continue;const[week,day]=key.split('-').map(Number);const{data:d,error}=await daysTable().insert({program_template_id:programId,week_number:week,day_number:day}).select().single();if(error)throw error;const{error:wError}=await workoutsTable().insert(items.map((x,i)=>({program_template_day_id:d.id,workout_template_id:x.workout_template_id,name:x.name,notes:x.notes||null,exercise_library_ids:x.exercise_library_ids,position:i})));if(wError)throw wError}}
export async function saveProgramTemplate(coachId:string,id:string|null,input:Omit<ProgramTemplate,'id'|'coach_id'|'created_at'|'updated_at'>,schedule:DraftSchedule){let programId=id;if(id){const{error}=await table().update({...input,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error}else{const{data,error}=await table().insert({coach_id:coachId,...input}).select().single();if(error)throw error;programId=data.id}await saveSchedule(programId!,schedule)}
export async function duplicateProgramTemplate(item:ProgramTemplate):Promise<ProgramTemplate>{const schedule=await getProgramSchedule(item.id);const{data,error}=await table().insert({coach_id:item.coach_id,name:`${item.name} Copy`,description:item.description,difficulty:item.difficulty,duration_weeks:item.duration_weeks}).select().single();if(error)throw error;await saveSchedule(data.id,schedule);return data}
export async function deleteProgramTemplate(id:string){const{error}=await table().delete().eq('id',id);if(error)throw error}
export async function assignProgramTemplateToPlayer(playerId:string,programTemplateId:string,startWeek:number):Promise<number>{const{data,error}=await(supabase.rpc as any)('assign_program_template_to_player',{p_player_id:playerId,p_program_template_id:programTemplateId,p_start_week:startWeek});if(error)throw error;return data}
