import{ supabase }from'../lib/supabase';export type TeamRole='viewer'|'chat'|'head_coach'|'sales';export interface TeamInvite{id:string;owner_coach_id:string;invite_key:string;role:TeamRole;status:string;created_at:string}export interface TeamMember{id:string;owner_coach_id:string;member_id:string;role:TeamRole;status:string;created_at:string;profile?:{name:string|null;email:string}}
const invites=()=>supabase.from('coach_team_invites' as never)as any;const members=()=>supabase.from('coach_team_members' as never)as any;const assignments=()=>supabase.from('coach_team_assignments' as never)as any;
export async function listTeamInvites(owner:string):Promise<TeamInvite[]>{const{data,error}=await invites().select('*').eq('owner_coach_id',owner).order('created_at',{ascending:false});if(error)throw error;return data??[]}
export async function createTeamInvite(role:TeamRole):Promise<TeamInvite>{const{data,error}=await(supabase.rpc as any)('create_team_invite',{p_role:role});if(error)throw error;return data}
export async function listTeamMembers(owner:string):Promise<TeamMember[]>{const{data,error}=await members().select('*').eq('owner_coach_id',owner);if(error)throw error;const ids=(data??[]).map((x:any)=>x.member_id);if(!ids.length)return[];const{data:profiles,error:pError}=await supabase.from('profiles').select('id,name,email').in('id',ids);if(pError)throw pError;return data.map((x:any)=>({...x,profile:profiles?.find(p=>p.id===x.member_id)}))}
export async function assignTeamClient(owner:string,member:string,player:string){const{error}=await assignments().upsert({owner_coach_id:owner,member_id:member,player_id:player},{onConflict:'owner_coach_id,member_id,player_id'});if(error)throw error}
export async function revokeTeamMember(id:string){const{error}=await members().update({status:'revoked'}).eq('id',id);if(error)throw error}
export async function checkTeamInvite(key:string){const{data,error}=await(supabase.rpc as any)('check_team_invite',{p_key:key});if(error)throw error;return data===true}
export async function claimTeamInvite(key:string){const{error}=await(supabase.rpc as any)('claim_team_invite',{p_key:key});if(error)throw error}
