import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Card, Screen, textStyles } from '../../components/Screen';
import { Button, Input } from '../../components/Controls';
import { useAuth } from '../../auth/AuthProvider';
import { supabase } from '../../lib/supabase';
import { colors } from '../../theme';
export default function AdminSupportScreen(){const{session}=useAuth();const[coaches,setCoaches]=useState<any[]|null>(null);const[selected,setSelected]=useState<any|null>(null);const[messages,setMessages]=useState<any[]|null>(null);const[body,setBody]=useState('');useEffect(()=>{supabase.from('profiles').select('id,name,email').eq('role','coach').order('name').then(({data})=>setCoaches(data??[]));},[]);useEffect(()=>{if(!selected)return;supabase.from('admin_messages').select('*').eq('coach_id',selected.id).order('created_at').limit(100).then(({data})=>setMessages(data??[]));const channel=supabase.channel(`mobile-admin-${selected.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'admin_messages',filter:`coach_id=eq.${selected.id}`},payload=>setMessages(current=>[...(current??[]),payload.new])).subscribe();return()=>{void supabase.removeChannel(channel)};},[selected]);async function send(){if(!body.trim()||!selected)return;const text=body.trim();setBody('');const{error}=await supabase.from('admin_messages').insert({coach_id:selected.id,sender_id:session!.user.id,body:text});if(error){setBody(text);Alert.alert('Could not send',error.message);}}return <Screen title="Support">{!selected?coaches===null?<ActivityIndicator/>:coaches.map(c=><Pressable key={c.id} onPress={()=>setSelected(c)}><Card><Text style={textStyles.heading}>{c.name||c.email}</Text><Text style={textStyles.muted}>Open support conversation</Text></Card></Pressable>):<><Text style={textStyles.heading}>{selected.name||selected.email}</Text>{messages===null?<ActivityIndicator/>:messages.map(m=><View key={m.id} style={[styles.bubble,m.sender_id===session!.user.id&&styles.mine]}><Text style={textStyles.body}>{m.body||`[${m.attachment_type}]`}</Text></View>)}<Input value={body} onChangeText={setBody} multiline placeholder="Reply to coach"/><Button onPress={send} disabled={!body.trim()}>SEND</Button><Button secondary onPress={()=>{setSelected(null);setMessages(null)}}>BACK</Button></>}</Screen>}
const styles=StyleSheet.create({bubble:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:12,padding:12,maxWidth:'85%'},mine:{alignSelf:'flex-end',backgroundColor:'#512715'}});
