-- Coach team invitations, roles, and client assignments.
create type public.team_role as enum ('viewer','chat','head_coach','sales');
create table public.coach_team_invites(id uuid primary key default gen_random_uuid(),owner_coach_id uuid not null references profiles(id) on delete cascade,invite_key text not null unique,role team_role not null,status text not null default 'pending' check(status in('pending','claimed','revoked')),claimed_by uuid references profiles(id),created_at timestamptz not null default now(),claimed_at timestamptz);
create table public.coach_team_members(id uuid primary key default gen_random_uuid(),owner_coach_id uuid not null references profiles(id) on delete cascade,member_id uuid not null references profiles(id) on delete cascade,role team_role not null,status text not null default 'active' check(status in('active','revoked')),created_at timestamptz not null default now(),unique(owner_coach_id,member_id));
create table public.coach_team_assignments(owner_coach_id uuid not null references profiles(id) on delete cascade,member_id uuid not null references profiles(id) on delete cascade,player_id uuid not null references profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key(owner_coach_id,member_id,player_id));
alter table coach_team_invites enable row level security;alter table coach_team_members enable row level security;alter table coach_team_assignments enable row level security;
create policy team_invites_owner on coach_team_invites for all to authenticated using(owner_coach_id=(select auth.uid())) with check(owner_coach_id=(select auth.uid()));
create policy team_members_owner_read on coach_team_members for select to authenticated using(owner_coach_id=(select auth.uid()) or member_id=(select auth.uid()));
create policy team_members_owner_write on coach_team_members for all to authenticated using(owner_coach_id=(select auth.uid())) with check(owner_coach_id=(select auth.uid()));
create policy team_assignments_parties on coach_team_assignments for select to authenticated using(owner_coach_id=(select auth.uid()) or member_id=(select auth.uid()));
create policy team_assignments_owner_write on coach_team_assignments for all to authenticated using(owner_coach_id=(select auth.uid())) with check(owner_coach_id=(select auth.uid()));
create or replace function public.create_team_invite(p_role team_role) returns coach_team_invites language plpgsql security definer set search_path=public as $$declare v coach_team_invites;begin if auth_role()<>'coach' then raise exception 'Access denied';end if;insert into coach_team_invites(owner_coach_id,invite_key,role)values((select auth.uid()),'TEAM-'||upper(substring(replace(gen_random_uuid()::text,'-',''),1,12)),p_role)returning * into v;return v;end$$;
create or replace function public.check_team_invite(p_key text) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from coach_team_invites where invite_key=upper(trim(p_key)) and status='pending')$$;
create or replace function public.claim_team_invite(p_key text) returns void language plpgsql security definer set search_path=public as $$declare v coach_team_invites;begin select * into v from coach_team_invites where invite_key=upper(trim(p_key)) and status='pending' for update;if not found then raise exception 'Invalid or used team key';end if;update profiles set role='coach' where id=(select auth.uid());insert into coach_team_members(owner_coach_id,member_id,role)values(v.owner_coach_id,(select auth.uid()),v.role);update coach_team_invites set status='claimed',claimed_by=(select auth.uid()),claimed_at=now() where id=v.id;end$$;
grant execute on function create_team_invite(team_role) to authenticated;grant execute on function check_team_invite(text) to anon,authenticated;grant execute on function claim_team_invite(text) to authenticated;
-- Team members can read assigned client identity/link information.
create policy profiles_team_assigned_read on profiles for select to authenticated using(exists(select 1 from coach_team_assignments a where a.member_id=(select auth.uid()) and a.player_id=profiles.id));
create policy links_team_assigned_read on coach_player_links for select to authenticated using(exists(select 1 from coach_team_assignments a where a.member_id=(select auth.uid()) and a.player_id=coach_player_links.player_id and a.owner_coach_id=coach_player_links.coach_id));
