import ExcelJS from 'exceljs';import * as DocumentPicker from 'expo-document-picker';import * as FileSystem from 'expo-file-system/legacy';import * as Sharing from 'expo-sharing';import { supabase } from './supabase';
const DOW:Record<string,number>={sun:0,sunday:0,mon:1,monday:1,tue:2,tuesday:2,wed:3,wednesday:3,thu:4,thursday:4,fri:5,friday:5,sat:6,saturday:6};
async function pick(){const r=await DocumentPicker.getDocumentAsync({type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',copyToCacheDirectory:true});if(r.canceled)return null;const a=r.assets[0];if(!a.size||a.size>2*1024*1024)throw new Error('Excel file must be smaller than 2 MB.');const b64=await FileSystem.readAsStringAsync(a.uri,{encoding:FileSystem.EncodingType.Base64});const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));if(bytes[0]!==0x50||bytes[1]!==0x4b)throw new Error('The selected file is not a valid Excel workbook.');return bytes.buffer}
function rows(ws:ExcelJS.Worksheet){const h=ws.getRow(1),headers=Array.from({length:h.cellCount},(_,i)=>h.getCell(i+1).text.trim().toLowerCase()),out:Record<string,string>[]=[];ws.eachRow((r,n)=>{if(n===1)return;const x=Object.fromEntries(headers.map((k,i)=>[k,r.getCell(i+1).text.trim()]));if(Object.values(x).some(Boolean))out.push(x)});if(!out.length)throw new Error('The Excel file has no data rows.');if(out.length>5000)throw new Error('The workbook cannot contain more than 5,000 rows.');return out}
export async function importProgramWorkbook(playerId:string){const buffer=await pick();if(!buffer)return null;const wb=new ExcelJS.Workbook();await wb.xlsx.load(buffer);const raw=rows(wb.worksheets[0]);const days=new Map<string,any>();for(const [i,r] of raw.entries()){const week=parseInt(r.week,10),d=r.day?.toLowerCase();if(!week||week<1||!(d in DOW))throw new Error(`Row ${i+2}: invalid week or day.`);const dow=DOW[d],key=`${week}|${dow}`,day=days.get(key)??{week,dow,day_type:r.day_type?.toLowerCase()==='rest'?'rest':'training',diet_plan:r.diet_plan||null,workouts:new Map()};days.set(key,day);if(day.day_type==='rest'||!r.workout||!r.exercise)continue;const w=day.workouts.get(r.workout)??{name:r.workout,exercises:[]};w.exercises.push({name:r.exercise,target_sets:r.target_sets?parseInt(r.target_sets,10):null,target_reps:r.target_reps||null,target_weight:r.target_weight||null,coach_comment:r.coach_comment||null,coach_video_url:r.coach_video_url||null,coach_video_is_external:!!r.coach_video_url});day.workouts.set(r.workout,w)}const payload=[...days.values()].map(d=>({...d,workouts:[...d.workouts.values()]}));const{data,error}=await supabase.rpc('replace_program_import',{p_player_id:playerId,p_days:payload});if(error)throw error;return data}
export async function importDietWorkbook(playerId:string){const buffer=await pick();if(!buffer)return null;const wb=new ExcelJS.Workbook();await wb.xlsx.load(buffer);const raw=rows(wb.worksheets[0]);const days=new Map<string,any>(),foods=new Map<string,string>();for(const[i,r]of raw.entries()){const week=parseInt(r.week,10),d=r.day?.toLowerCase(),type=r.meal_type?.toLowerCase();if(!week||!(d in DOW)||!['meal','snack'].includes(type)||!r.meal_label||!r.food)throw new Error(`Row ${i+2}: invalid diet information.`);const key=`${week}|${DOW[d]}`,day=days.get(key)??{week,dow:DOW[d],comment:r.coach_comment||null,meals:new Map()},mk=`${type}|${r.meal_label.toLowerCase()}`,meal=day.meals.get(mk)??{type,label:r.meal_label,content:'',items:[]};meal.items.push({food:r.food,grams:r.grams});day.meals.set(mk,meal);days.set(key,day);foods.set(r.food.toLowerCase(),r.food)}const payload=[...days.values()].map(d=>({...d,meals:[...d.meals.values()]}));const{data,error}=await supabase.rpc('replace_diet_import',{p_player_id:playerId,p_days:payload,p_foods:[...foods.values()]});if(error)throw error;return data}
async function share(name:string,sheet:string,headers:string[],examples:(string|number)[][]){const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet(sheet);ws.addRows([headers,...examples]);const buffer=await wb.xlsx.writeBuffer(),path=`${FileSystem.cacheDirectory}${name}`;let binary='';for(const b of new Uint8Array(buffer as ArrayBuffer))binary+=String.fromCharCode(b);await FileSystem.writeAsStringAsync(path,btoa(binary),{encoding:FileSystem.EncodingType.Base64});await Sharing.shareAsync(path,{mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
export const shareProgramTemplate=()=>share('program-template.xlsx','Program',['week','day','day_type','workout','exercise','target_sets','target_reps','target_weight','coach_comment','coach_video_url','diet_plan'],[[1,'Sat','training','Upper Body','Bench Press',3,'8-12','60 kg','','','']]);
export const shareDietTemplate=()=>share('diet-template.xlsx','Diet',['week','day','meal_type','meal_label','food','grams','coach_comment'],[[1,'Sat','meal','Meal 1','Eggs',150,'']]);
